import { jsPDF } from 'jspdf'
import type { TripPlan } from '@/components/trip-planner/types'

export function tripPlanPdfFileName(tripPlan: TripPlan): string {
  const slug =
    tripPlan.destination
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 60) || 'trip'
  return `unilife-trip-plan-${slug}.pdf`
}

function formatRs(n: number) {
  return `Rs ${Math.round(n).toLocaleString('en-LK')}`
}

export function buildTripPlanPdf(tripPlan: TripPlan): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageH = doc.internal.pageSize.getHeight()
  const margin = 14
  const maxW = doc.internal.pageSize.getWidth() - margin * 2
  let y = 18

  const ensureSpace = (h: number) => {
    if (y + h > pageH - 14) {
      doc.addPage()
      y = 18
    }
  }

  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(`Trip plan: ${tripPlan.destination}`, margin, y)
  y += 10

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const sub = `${tripPlan.days} days · ${tripPlan.travelers} traveler(s) · ${tripPlan.tier} · ${formatRs(tripPlan.perPersonBudget)}/person`
  for (const line of doc.splitTextToSize(sub, maxW)) {
    ensureSpace(6)
    doc.text(line, margin, y)
    y += 5
  }
  y += 4

  if (tripPlan.warning) {
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(160, 90, 0)
    for (const line of doc.splitTextToSize(`Note: ${tripPlan.warning}`, maxW)) {
      ensureSpace(6)
      doc.text(line, margin, y)
      y += 5
    }
    doc.setTextColor(0, 0, 0)
    doc.setFont('helvetica', 'normal')
    y += 4
  }

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  ensureSpace(8)
  doc.text(`Budget breakdown — Total ${formatRs(tripPlan.totalBudget)}`, margin, y)
  y += 8
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const bd = tripPlan.breakdown
  for (const [label, amt] of [
    ['Stay', bd.stay],
    ['Travel', bd.travel],
    ['Food', bd.food],
    ['Activities', bd.activities],
    ['Emergency', bd.emergency],
  ] as const) {
    ensureSpace(6)
    doc.text(`${label}: ${formatRs(amt)}`, margin, y)
    y += 5
  }
  y += 4

  const addParagraph = (title: string, body: string) => {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    ensureSpace(8)
    doc.text(title, margin, y)
    y += 6
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    for (const line of doc.splitTextToSize(body, maxW)) {
      ensureSpace(5)
      doc.text(line, margin, y)
      y += 5
    }
    y += 3
  }

  addParagraph('Stay', tripPlan.hotelReco)
  addParagraph('Travel', tripPlan.travelReco)
  addParagraph('Food', tripPlan.foodReco)

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  ensureSpace(8)
  doc.text('Day-by-day itinerary', margin, y)
  y += 8
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')

  for (const d of tripPlan.dailyPlan) {
    doc.setFont('helvetica', 'bold')
    ensureSpace(8)
    doc.text(`Day ${d.day}`, margin, y)
    y += 6
    doc.setFont('helvetica', 'normal')
    for (const block of [
      `Morning: ${d.morning}`,
      `Afternoon: ${d.afternoon}`,
      `Evening: ${d.evening}`,
      `Meals: ${d.meals}`,
    ]) {
      for (const line of doc.splitTextToSize(block, maxW)) {
        ensureSpace(5)
        doc.text(line, margin, y)
        y += 5
      }
    }
    y += 2
  }

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  ensureSpace(8)
  doc.text('Travel tips', margin, y)
  y += 8
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  for (const tip of tripPlan.tips) {
    for (const line of doc.splitTextToSize(`• ${tip}`, maxW)) {
      ensureSpace(5)
      doc.text(line, margin, y)
      y += 5
    }
  }

  y += 4
  ensureSpace(6)
  doc.setFontSize(8)
  doc.setTextColor(120, 120, 120)
  doc.text(`Generated by UniLife · ${new Date().toLocaleString()}`, margin, y)
  doc.setTextColor(0, 0, 0)

  return doc
}

export function downloadTripPlanPdf(tripPlan: TripPlan) {
  buildTripPlanPdf(tripPlan).save(tripPlanPdfFileName(tripPlan))
}

export function tripPlanPdfBlob(tripPlan: TripPlan): Blob {
  return buildTripPlanPdf(tripPlan).output('blob')
}
