// Dashboard Mock Data
export const todayClasses = [
  {
    id: 1,
    name: "Data Structures & Algorithms",
    code: "CS201",
    time: "09:00 AM - 10:30 AM",
    room: "LH-101",
    professor: "Dr. Sarah Johnson",
    color: "#4F46E5",
  },
  {
    id: 2,
    name: "Database Management Systems",
    code: "CS301",
    time: "11:00 AM - 12:30 PM",
    room: "LH-205",
    professor: "Prof. Michael Chen",
    color: "#22C55E",
  },
  {
    id: 3,
    name: "Web Development",
    code: "CS401",
    time: "02:00 PM - 03:30 PM",
    room: "Lab-302",
    professor: "Dr. Emily Rodriguez",
    color: "#F59E0B",
  },
];

export const upcomingDeadlines = [
  {
    id: 1,
    title: "DSA Assignment 3",
    course: "CS201",
    dueDate: "2026-01-27",
    dueTime: "11:59 PM",
    progress: 75,
    status: "in-progress",
  },
  {
    id: 2,
    title: "Database Project Proposal",
    course: "CS301",
    dueDate: "2026-01-28",
    dueTime: "05:00 PM",
    progress: 30,
    status: "in-progress",
  },
  {
    id: 3,
    title: "Web Dev Portfolio",
    course: "CS401",
    dueDate: "2026-01-30",
    dueTime: "11:59 PM",
    progress: 0,
    status: "not-started",
  },
  {
    id: 4,
    title: "Research Paper Review",
    course: "CS501",
    dueDate: "2026-02-01",
    dueTime: "11:59 PM",
    progress: 100,
    status: "completed",
  },
];

export const notifications = [
  {
    id: 1,
    type: "announcement",
    title: "Campus Closed Monday",
    message: "University will remain closed on Monday due to maintenance.",
    time: "2 hours ago",
    read: false,
  },
  {
    id: 2,
    type: "deadline",
    title: "Assignment Due Soon",
    message: "DSA Assignment 3 is due in 2 days.",
    time: "5 hours ago",
    read: false,
  },
  {
    id: 3,
    type: "event",
    title: "Tech Fest Registration",
    message: "Registration for Tech Fest 2026 is now open!",
    time: "1 day ago",
    read: true,
  },
  {
    id: 4,
    type: "group",
    title: "Study Group Meeting",
    message: "DSA study group meeting scheduled for tomorrow at 4 PM.",
    time: "1 day ago",
    read: true,
  },
];

// Timetable Mock Data
export const weeklySchedule = [
  {
    day: "Monday",
    classes: [
      { id: 1, name: "Data Structures", code: "CS201", time: "09:00 - 10:30", room: "LH-101", color: "#4F46E5" },
      { id: 2, name: "Database Systems", code: "CS301", time: "11:00 - 12:30", room: "LH-205", color: "#22C55E" },
      { id: 3, name: "Web Development", code: "CS401", time: "14:00 - 15:30", room: "Lab-302", color: "#F59E0B" },
    ],
  },
  {
    day: "Tuesday",
    classes: [
      { id: 4, name: "Computer Networks", code: "CS302", time: "10:00 - 11:30", room: "LH-103", color: "#EF4444" },
      { id: 5, name: "Software Engineering", code: "CS402", time: "13:00 - 14:30", room: "LH-201", color: "#8B5CF6" },
    ],
  },
  {
    day: "Wednesday",
    classes: [
      { id: 6, name: "Data Structures Lab", code: "CS201L", time: "09:00 - 12:00", room: "Lab-101", color: "#4F46E5" },
      { id: 7, name: "Web Development", code: "CS401", time: "14:00 - 15:30", room: "Lab-302", color: "#F59E0B" },
    ],
  },
  {
    day: "Thursday",
    classes: [
      { id: 8, name: "Database Systems", code: "CS301", time: "09:00 - 10:30", room: "LH-205", color: "#22C55E" },
      { id: 9, name: "Computer Networks", code: "CS302", time: "11:00 - 12:30", room: "LH-103", color: "#EF4444" },
      { id: 10, name: "Software Engineering", code: "CS402", time: "14:00 - 15:30", room: "LH-201", color: "#8B5CF6" },
    ],
  },
  {
    day: "Friday",
    classes: [
      { id: 11, name: "Data Structures", code: "CS201", time: "09:00 - 10:30", room: "LH-101", color: "#4F46E5" },
      { id: 12, name: "Database Lab", code: "CS301L", time: "11:00 - 14:00", room: "Lab-201", color: "#22C55E" },
    ],
  },
];

// Assignments Mock Data
export const assignments = [
  {
    id: 1,
    title: "DSA Assignment 3: Binary Trees",
    course: "Data Structures & Algorithms",
    courseCode: "CS201",
    dueDate: "2026-01-27",
    dueTime: "11:59 PM",
    description: "Implement binary tree operations including insertion, deletion, and traversal algorithms.",
    progress: 75,
    status: "in-progress",
    priority: "high",
  },
  {
    id: 2,
    title: "Database Project Proposal",
    course: "Database Management Systems",
    courseCode: "CS301",
    dueDate: "2026-01-28",
    dueTime: "05:00 PM",
    description: "Submit a detailed proposal for the semester database project including ER diagrams.",
    progress: 30,
    status: "in-progress",
    priority: "high",
  },
  {
    id: 3,
    title: "Web Development Portfolio",
    course: "Web Development",
    courseCode: "CS401",
    dueDate: "2026-01-30",
    dueTime: "11:59 PM",
    description: "Create a personal portfolio website showcasing your projects and skills.",
    progress: 0,
    status: "not-started",
    priority: "medium",
  },
  {
    id: 4,
    title: "Network Protocol Analysis",
    course: "Computer Networks",
    courseCode: "CS302",
    dueDate: "2026-02-02",
    dueTime: "11:59 PM",
    description: "Analyze TCP/IP protocols using Wireshark and document findings.",
    progress: 0,
    status: "not-started",
    priority: "low",
  },
  {
    id: 5,
    title: "Software Requirements Document",
    course: "Software Engineering",
    courseCode: "CS402",
    dueDate: "2026-01-25",
    dueTime: "11:59 PM",
    description: "Complete SRS document for the team project.",
    progress: 100,
    status: "completed",
    priority: "high",
  },
];

// Courses Mock Data
export const courses = [
  {
    id: 1,
    name: "Data Structures & Algorithms",
    code: "CS201",
    professor: "Dr. Sarah Johnson",
    credits: 4,
    color: "#4F46E5",
    progress: 65,
    grade: "A-",
  },
  {
    id: 2,
    name: "Database Management Systems",
    code: "CS301",
    professor: "Prof. Michael Chen",
    credits: 4,
    color: "#22C55E",
    progress: 70,
    grade: "B+",
  },
  {
    id: 3,
    name: "Web Development",
    code: "CS401",
    professor: "Dr. Emily Rodriguez",
    credits: 3,
    color: "#F59E0B",
    progress: 55,
    grade: "A",
  },
  {
    id: 4,
    name: "Computer Networks",
    code: "CS302",
    professor: "Prof. David Kim",
    credits: 3,
    color: "#EF4444",
    progress: 60,
    grade: "B",
  },
  {
    id: 5,
    name: "Software Engineering",
    code: "CS402",
    professor: "Dr. Lisa Wang",
    credits: 3,
    color: "#8B5CF6",
    progress: 75,
    grade: "A-",
  },
];

// Notes Mock Data
export const notes = [
  {
    id: 1,
    title: "DSA Complete Notes - Trees & Graphs",
    course: "CS201",
    courseName: "Data Structures & Algorithms",
    uploader: "Alex Thompson",
    uploadDate: "2026-01-20",
    fileType: "pdf",
    fileSize: "2.4 MB",
    upvotes: 156,
    downloads: 342,
  },
  {
    id: 2,
    title: "SQL Cheat Sheet",
    course: "CS301",
    courseName: "Database Management Systems",
    uploader: "Emma Wilson",
    uploadDate: "2026-01-18",
    fileType: "pdf",
    fileSize: "1.2 MB",
    upvotes: 203,
    downloads: 489,
  },
  {
    id: 3,
    title: "React Hooks Tutorial",
    course: "CS401",
    courseName: "Web Development",
    uploader: "Ryan Garcia",
    uploadDate: "2026-01-22",
    fileType: "docx",
    fileSize: "856 KB",
    upvotes: 89,
    downloads: 178,
  },
  {
    id: 4,
    title: "TCP/IP Protocol Summary",
    course: "CS302",
    courseName: "Computer Networks",
    uploader: "Sophia Lee",
    uploadDate: "2026-01-15",
    fileType: "pdf",
    fileSize: "3.1 MB",
    upvotes: 124,
    downloads: 267,
  },
  {
    id: 5,
    title: "Agile Methodology Notes",
    course: "CS402",
    courseName: "Software Engineering",
    uploader: "James Miller",
    uploadDate: "2026-01-19",
    fileType: "pptx",
    fileSize: "5.2 MB",
    upvotes: 67,
    downloads: 145,
  },
];

// Study Groups Mock Data
export const studyGroups = [
  {
    id: 1,
    name: "DSA Warriors",
    course: "CS201",
    courseName: "Data Structures & Algorithms",
    members: 12,
    maxMembers: 15,
    nextMeeting: "2026-01-26 16:00",
    meetingLocation: "Library Room 3A",
    description: "Weekly problem-solving sessions for DSA assignments and exam prep.",
    isJoined: true,
    avatar: "🔥",
  },
  {
    id: 2,
    name: "SQL Masters",
    course: "CS301",
    courseName: "Database Management Systems",
    members: 8,
    maxMembers: 10,
    nextMeeting: "2026-01-27 14:00",
    meetingLocation: "Online - Discord",
    description: "Focus on SQL queries, normalization, and database design.",
    isJoined: false,
    avatar: "💾",
  },
  {
    id: 3,
    name: "Web Dev Wizards",
    course: "CS401",
    courseName: "Web Development",
    members: 15,
    maxMembers: 20,
    nextMeeting: "2026-01-28 18:00",
    meetingLocation: "Tech Hub Cafe",
    description: "Build projects together, share resources, and learn new frameworks.",
    isJoined: true,
    avatar: "🚀",
  },
  {
    id: 4,
    name: "Network Ninjas",
    course: "CS302",
    courseName: "Computer Networks",
    members: 6,
    maxMembers: 12,
    nextMeeting: "2026-01-29 15:00",
    meetingLocation: "Lab-103",
    description: "Hands-on networking labs and protocol analysis sessions.",
    isJoined: false,
    avatar: "🌐",
  },
];

// Chat Messages for Study Groups
export const groupChatMessages = [
  {
    id: 1,
    groupId: 1,
    sender: "Alex Thompson",
    message: "Hey everyone! Ready for today's session on AVL trees?",
    time: "3:45 PM",
    isMe: false,
  },
  {
    id: 2,
    groupId: 1,
    sender: "You",
    message: "Yes! I've been struggling with rotations though 😅",
    time: "3:47 PM",
    isMe: true,
  },
  {
    id: 3,
    groupId: 1,
    sender: "Emma Wilson",
    message: "I found a great visualization tool, will share during the meeting!",
    time: "3:50 PM",
    isMe: false,
  },
  {
    id: 4,
    groupId: 1,
    sender: "Ryan Garcia",
    message: "Perfect timing, I need help with the assignment too",
    time: "3:52 PM",
    isMe: false,
  },
];

// Marketplace Mock Data
export const marketplaceItems = [
  {
    id: 1,
    title: "DSA Textbook - Cormen (Like New)",
    category: "Textbooks",
    price: 4500,
    originalPrice: 8900,
    seller: "John Smith",
    sellerRating: 4.8,
    sellerReviews: 23,
    condition: "Like New",
    image: "📚",
    postedDate: "2026-01-23",
    description: "Introduction to Algorithms by Cormen. Used for one semester, no highlights or marks.",
  },
  {
    id: 2,
    title: "MacBook Pro 2024 M3",
    category: "Devices",
    price: 450000,
    originalPrice: 650000,
    seller: "Sarah Lee",
    sellerRating: 4.9,
    sellerReviews: 15,
    condition: "Excellent",
    image: "💻",
    postedDate: "2026-01-22",
    description: "14-inch MacBook Pro, M3 chip, 16GB RAM. Comes with charger and case.",
  },
  {
    id: 3,
    title: "Database Systems Notes Bundle",
    category: "Notes",
    price: 1500,
    originalPrice: null,
    seller: "Mike Johnson",
    sellerRating: 4.7,
    sellerReviews: 45,
    condition: "Digital",
    image: "📝",
    postedDate: "2026-01-24",
    description: "Complete semester notes with solved examples and practice problems.",
  },
  {
    id: 4,
    title: "Scientific Calculator TI-84",
    category: "Devices",
    price: 18000,
    originalPrice: 35000,
    seller: "Emma Davis",
    sellerRating: 4.6,
    sellerReviews: 12,
    condition: "Good",
    image: "🔢",
    postedDate: "2026-01-21",
    description: "TI-84 Plus graphing calculator. Works perfectly, minor scratches.",
  },
  {
    id: 5,
    title: "Web Development Bootcamp Notes",
    category: "Notes",
    price: 2000,
    originalPrice: null,
    seller: "Chris Park",
    sellerRating: 4.9,
    sellerReviews: 67,
    condition: "Digital",
    image: "🌐",
    postedDate: "2026-01-20",
    description: "Comprehensive notes covering HTML, CSS, JavaScript, React, and Node.js.",
  },
  {
    id: 6,
    title: "Engineering Drawing Kit",
    category: "Supplies",
    price: 2500,
    originalPrice: 5000,
    seller: "Ana Martinez",
    sellerRating: 4.5,
    sellerReviews: 8,
    condition: "Good",
    image: "📐",
    postedDate: "2026-01-19",
    description: "Complete drawing kit with compass, rulers, and templates.",
  },
];

// Part-time Jobs Mock Data
export const partTimeJobs = [
  {
    id: 1,
    title: "Library Assistant",
    company: "University Library",
    location: "On-campus",
    type: "Part-time",
    pay: 500,
    payType: "hour",
    schedule: ["Weekday", "Evening"],
    description: "Help students find resources, manage book returns, and maintain library organization.",
    requirements: ["Good communication", "Organized", "Basic computer skills"],
    postedDate: "2026-01-22",
    deadline: "2026-02-01",
  },
  {
    id: 2,
    title: "Research Assistant",
    company: "CS Department",
    location: "On-campus",
    type: "Part-time",
    pay: 600,
    payType: "hour",
    schedule: ["Weekday", "Flexible"],
    description: "Assist professors with research projects, data collection, and analysis.",
    requirements: ["Programming skills", "Research interest", "GPA 3.5+"],
    postedDate: "2026-01-20",
    deadline: "2026-01-30",
  },
  {
    id: 3,
    title: "Campus Tour Guide",
    company: "Admissions Office",
    location: "On-campus",
    type: "Part-time",
    pay: 450,
    payType: "hour",
    schedule: ["Weekend", "Flexible"],
    description: "Lead campus tours for prospective students and their families.",
    requirements: ["Outgoing personality", "Knowledge of campus", "Public speaking"],
    postedDate: "2026-01-23",
    deadline: "2026-02-05",
  },
  {
    id: 4,
    title: "Tutoring - Mathematics",
    company: "Academic Support Center",
    location: "On-campus",
    type: "Part-time",
    pay: 750,
    payType: "hour",
    schedule: ["Evening", "Weekend"],
    description: "Provide tutoring sessions for students in calculus and linear algebra.",
    requirements: ["Strong math background", "Teaching experience preferred", "Patient"],
    postedDate: "2026-01-21",
    deadline: "2026-02-10",
  },
  {
    id: 5,
    title: "Social Media Manager",
    company: "Student Union",
    location: "Remote",
    type: "Part-time",
    pay: 550,
    payType: "hour",
    schedule: ["Flexible", "Remote"],
    description: "Manage social media accounts, create content, and engage with student community.",
    requirements: ["Social media savvy", "Creative", "Basic design skills"],
    postedDate: "2026-01-24",
    deadline: "2026-02-15",
  },
  {
    id: 6,
    title: "Cafe Barista",
    company: "Campus Coffee",
    location: "Nearby",
    type: "Part-time",
    pay: 400,
    payType: "hour",
    schedule: ["Weekend", "Morning"],
    description: "Prepare coffee drinks, serve customers, and maintain cleanliness.",
    requirements: ["Customer service", "Fast learner", "Early mornings OK"],
    postedDate: "2026-01-19",
    deadline: "2026-01-28",
  },
];

// Food Ordering Mock Data
export const foodVendors = [
  {
    id: 1,
    name: "Campus Canteen",
    type: "Canteen",
    rating: 4.2,
    reviews: 234,
    deliveryTime: "15-20 min",
    deliveryFee: 0,
    image: "🍽️",
    isOpen: true,
  },
  {
    id: 2,
    name: "Pizza Palace",
    type: "Restaurant",
    rating: 4.5,
    reviews: 189,
    deliveryTime: "25-35 min",
    deliveryFee: 150,
    image: "🍕",
    isOpen: true,
  },
  {
    id: 3,
    name: "Healthy Bites",
    type: "Cafe",
    rating: 4.7,
    reviews: 156,
    deliveryTime: "20-30 min",
    deliveryFee: 100,
    image: "🥗",
    isOpen: true,
  },
  {
    id: 4,
    name: "Dragon Wok",
    type: "Restaurant",
    rating: 4.4,
    reviews: 278,
    deliveryTime: "30-40 min",
    deliveryFee: 200,
    image: "🥡",
    isOpen: false,
  },
];

export const menuItems = [
  // Campus Canteen
  { id: 1, vendorId: 1, name: "Chicken Rice Bowl", price: 450, category: "Main", image: "🍚", popular: true },
  { id: 2, vendorId: 1, name: "Vegetable Curry", price: 350, category: "Main", image: "🍛", popular: false },
  { id: 3, vendorId: 1, name: "Grilled Sandwich", price: 280, category: "Snacks", image: "🥪", popular: true },
  { id: 4, vendorId: 1, name: "Fresh Juice", price: 180, category: "Drinks", image: "🧃", popular: false },
  // Pizza Palace
  { id: 5, vendorId: 2, name: "Margherita Pizza", price: 1200, category: "Pizza", image: "🍕", popular: true },
  { id: 6, vendorId: 2, name: "Pepperoni Pizza", price: 1500, category: "Pizza", image: "🍕", popular: true },
  { id: 7, vendorId: 2, name: "Garlic Bread", price: 450, category: "Sides", image: "🥖", popular: false },
  { id: 8, vendorId: 2, name: "Coke", price: 150, category: "Drinks", image: "🥤", popular: false },
  // Healthy Bites
  { id: 9, vendorId: 3, name: "Caesar Salad", price: 650, category: "Salads", image: "🥗", popular: true },
  { id: 10, vendorId: 3, name: "Avocado Toast", price: 550, category: "Breakfast", image: "🥑", popular: true },
  { id: 11, vendorId: 3, name: "Smoothie Bowl", price: 750, category: "Bowls", image: "🫐", popular: false },
  { id: 12, vendorId: 3, name: "Green Juice", price: 400, category: "Drinks", image: "🥬", popular: false },
];

// Laundry Mock Data
export const laundryServices = [
  {
    id: 1,
    name: "QuickWash Campus",
    rating: 4.6,
    reviews: 189,
    pricePerKg: 250,
    minOrder: 2,
    deliveryTime: "24-48 hours",
    hasPickup: true,
    hasDelivery: true,
    image: "🧺",
  },
  {
    id: 2,
    name: "Premium Dry Clean",
    rating: 4.8,
    reviews: 134,
    pricePerKg: 400,
    minOrder: 1,
    deliveryTime: "48-72 hours",
    hasPickup: true,
    hasDelivery: true,
    image: "👔",
  },
  {
    id: 3,
    name: "Express Laundry",
    rating: 4.4,
    reviews: 256,
    pricePerKg: 300,
    minOrder: 1.5,
    deliveryTime: "12-24 hours",
    hasPickup: true,
    hasDelivery: false,
    image: "⚡",
  },
];

export const laundryPricing = [
  { type: "Regular Wash", pricePerKg: 250 },
  { type: "Dry Clean", pricePerItem: 600 },
  { type: "Iron Only", pricePerItem: 150 },
  { type: "Bedding (per piece)", pricePerItem: 800 },
  { type: "Express (same day)", pricePerKg: 450 },
];

export const laundryOrders = [
  {
    id: "LD001",
    service: "QuickWash Campus",
    status: "ready",
    items: "5kg Regular Wash",
    total: 1250,
    pickupTime: "2026-01-25 10:00 AM",
    deliveryTime: "2026-01-26 06:00 PM",
  },
  {
    id: "LD002",
    service: "Premium Dry Clean",
    status: "processing",
    items: "2 Shirts, 1 Suit",
    total: 2400,
    pickupTime: "2026-01-24 02:00 PM",
    deliveryTime: "2026-01-27 04:00 PM",
  },
];

// Rides Mock Data
export const rideOptions = [
  {
    id: 1,
    type: "Bike",
    icon: "🏍️",
    basePrice: 100,
    pricePerKm: 30,
    eta: "5-10 min",
    capacity: 1,
    description: "Quick and affordable",
  },
  {
    id: 2,
    type: "Three-Wheeler",
    icon: "🛺",
    basePrice: 150,
    pricePerKm: 50,
    eta: "8-15 min",
    capacity: 3,
    description: "Budget-friendly option",
  },
  {
    id: 3,
    type: "Car",
    icon: "🚗",
    basePrice: 250,
    pricePerKm: 80,
    eta: "10-20 min",
    capacity: 4,
    description: "Comfortable rides",
  },
  {
    id: 4,
    type: "Premium Car",
    icon: "🚘",
    basePrice: 400,
    pricePerKm: 120,
    eta: "10-15 min",
    capacity: 4,
    description: "Premium experience",
  },
];

export const popularLocations = [
  { id: 1, name: "University Main Gate", type: "campus" },
  { id: 2, name: "Library Building", type: "campus" },
  { id: 3, name: "Sports Complex", type: "campus" },
  { id: 4, name: "Student Hostel A", type: "campus" },
  { id: 5, name: "City Mall", type: "nearby" },
  { id: 6, name: "Central Station", type: "nearby" },
  { id: 7, name: "Airport", type: "city" },
  { id: 8, name: "Bus Terminal", type: "city" },
];

// Trip Planner Mock Data
export const tripDestinations = [
  { id: 1, name: "Sigiriya", image: "🏰", popular: true },
  { id: 2, name: "Kandy", image: "🛕", popular: true },
  { id: 3, name: "Galle", image: "🏖️", popular: true },
  { id: 4, name: "Ella", image: "🏔️", popular: true },
  { id: 5, name: "Mirissa", image: "🐋", popular: false },
  { id: 6, name: "Nuwara Eliya", image: "🍃", popular: false },
  { id: 7, name: "Anuradhapura", image: "🛕", popular: false },
  { id: 8, name: "Trincomalee", image: "🌊", popular: false },
];

export const tripPlans = {
  "Sigiriya": {
    days: [
      {
        day: 1,
        title: "Ancient Rock Fortress",
        activities: [
          { time: "06:00 AM", activity: "Early climb to Sigiriya Rock", cost: 5000 },
          { time: "09:00 AM", activity: "Explore Frescoes & Mirror Wall", cost: 0 },
          { time: "11:00 AM", activity: "Lion's Paw & Summit", cost: 0 },
          { time: "01:00 PM", activity: "Traditional Rice & Curry Lunch", cost: 800 },
          { time: "03:00 PM", activity: "Pidurangala Rock Hike", cost: 500 },
          { time: "06:00 PM", activity: "Sunset views of Sigiriya", cost: 0 },
          { time: "08:00 PM", activity: "Dinner at Village Restaurant", cost: 1200 },
        ],
      },
      {
        day: 2,
        title: "Safari & Village Life",
        activities: [
          { time: "05:30 AM", activity: "Minneriya Safari (Elephants)", cost: 6000 },
          { time: "10:00 AM", activity: "Breakfast at Hotel", cost: 600 },
          { time: "12:00 PM", activity: "Village cycling tour", cost: 1500 },
          { time: "01:30 PM", activity: "Lunch with local family", cost: 800 },
          { time: "03:00 PM", activity: "Dambulla Cave Temple", cost: 1500 },
          { time: "06:00 PM", activity: "Return & Rest", cost: 0 },
          { time: "08:00 PM", activity: "Sri Lankan Buffet Dinner", cost: 1800 },
        ],
      },
      {
        day: 3,
        title: "Heritage & Departure",
        activities: [
          { time: "08:00 AM", activity: "Breakfast", cost: 600 },
          { time: "10:00 AM", activity: "Polonnaruwa Ancient City", cost: 3500 },
          { time: "01:00 PM", activity: "Lunch", cost: 800 },
          { time: "03:00 PM", activity: "Souvenir Shopping", cost: 2500 },
          { time: "05:00 PM", activity: "Departure", cost: 0 },
        ],
      },
    ],
    budget: {
      transport: 12000,
      food: 8000,
      stay: 9000,
      activities: 18000,
    },
  },
  "Kandy": {
    days: [
      {
        day: 1,
        title: "Sacred City Exploration",
        activities: [
          { time: "09:00 AM", activity: "Arrival & Check-in", cost: 0 },
          { time: "10:30 AM", activity: "Temple of the Tooth Relic", cost: 2000 },
          { time: "01:00 PM", activity: "Lunch at The Empire Cafe", cost: 1200 },
          { time: "03:00 PM", activity: "Royal Botanical Gardens", cost: 1500 },
          { time: "05:30 PM", activity: "Kandy Lake Walk", cost: 0 },
          { time: "07:00 PM", activity: "Kandyan Dance Show", cost: 2000 },
          { time: "09:00 PM", activity: "Dinner", cost: 1500 },
        ],
      },
      {
        day: 2,
        title: "Tea Country Adventure",
        activities: [
          { time: "07:00 AM", activity: "Breakfast at Hotel", cost: 600 },
          { time: "08:30 AM", activity: "Train to Tea Plantation", cost: 500 },
          { time: "10:00 AM", activity: "Tea Factory Tour", cost: 1000 },
          { time: "12:00 PM", activity: "Tea Tasting Experience", cost: 500 },
          { time: "01:30 PM", activity: "Lunch with Valley View", cost: 1500 },
          { time: "03:00 PM", activity: "Spice Garden Visit", cost: 0 },
          { time: "05:00 PM", activity: "Return to Kandy", cost: 500 },
          { time: "08:00 PM", activity: "Dinner at Devon Restaurant", cost: 1800 },
        ],
      },
      {
        day: 3,
        title: "Culture & Crafts",
        activities: [
          { time: "08:00 AM", activity: "Breakfast", cost: 600 },
          { time: "09:30 AM", activity: "Gem Museum Visit", cost: 0 },
          { time: "11:00 AM", activity: "Batik Factory Tour", cost: 0 },
          { time: "01:00 PM", activity: "Local Lunch", cost: 800 },
          { time: "02:30 PM", activity: "Kandy Market Shopping", cost: 3000 },
          { time: "05:00 PM", activity: "Checkout & Departure", cost: 0 },
        ],
      },
    ],
    budget: {
      transport: 8000,
      food: 10000,
      stay: 10500,
      activities: 10500,
    },
  },
  "Galle": {
    days: [
      {
        day: 1,
        title: "Dutch Colonial Heritage",
        activities: [
          { time: "09:00 AM", activity: "Arrival & Check-in", cost: 0 },
          { time: "10:30 AM", activity: "Galle Fort Walking Tour", cost: 0 },
          { time: "12:00 PM", activity: "Dutch Reformed Church", cost: 0 },
          { time: "01:00 PM", activity: "Lunch at Fort Cafe", cost: 1500 },
          { time: "03:00 PM", activity: "Maritime Museum", cost: 500 },
          { time: "05:00 PM", activity: "Flag Rock Sunset", cost: 0 },
          { time: "07:30 PM", activity: "Seafood Dinner at Fort", cost: 2500 },
        ],
      },
      {
        day: 2,
        title: "Beach & Wildlife",
        activities: [
          { time: "07:00 AM", activity: "Breakfast at Hotel", cost: 800 },
          { time: "08:30 AM", activity: "Unawatuna Beach", cost: 0 },
          { time: "11:00 AM", activity: "Japanese Peace Pagoda", cost: 0 },
          { time: "01:00 PM", activity: "Beach Lunch", cost: 1200 },
          { time: "03:00 PM", activity: "Sea Turtle Hatchery", cost: 1000 },
          { time: "05:00 PM", activity: "Stilt Fishermen Watch", cost: 500 },
          { time: "07:00 PM", activity: "Dinner in Galle", cost: 1800 },
        ],
      },
    ],
    budget: {
      transport: 7000,
      food: 9000,
      stay: 12000,
      activities: 6000,
    },
  },
  "Ella": {
    days: [
      {
        day: 1,
        title: "Scenic Train & Hiking",
        activities: [
          { time: "06:00 AM", activity: "Scenic Train from Kandy", cost: 300 },
          { time: "12:00 PM", activity: "Arrival & Check-in", cost: 0 },
          { time: "01:00 PM", activity: "Lunch at Cafe Chill", cost: 1000 },
          { time: "03:00 PM", activity: "Little Adam's Peak Hike", cost: 0 },
          { time: "06:00 PM", activity: "Sunset at Summit", cost: 0 },
          { time: "08:00 PM", activity: "Dinner at Ella Village", cost: 1200 },
        ],
      },
      {
        day: 2,
        title: "Waterfalls & Adventure",
        activities: [
          { time: "05:00 AM", activity: "Ella Rock Sunrise Hike", cost: 0 },
          { time: "09:00 AM", activity: "Breakfast at Hotel", cost: 600 },
          { time: "11:00 AM", activity: "Nine Arch Bridge", cost: 0 },
          { time: "01:00 PM", activity: "Lunch", cost: 800 },
          { time: "02:30 PM", activity: "Ravana Falls", cost: 0 },
          { time: "04:00 PM", activity: "Flying Ravana Zipline", cost: 4000 },
          { time: "06:00 PM", activity: "Rest & Relax", cost: 0 },
          { time: "08:00 PM", activity: "BBQ Dinner", cost: 1800 },
        ],
      },
      {
        day: 3,
        title: "Tea & Departure",
        activities: [
          { time: "07:00 AM", activity: "Breakfast", cost: 600 },
          { time: "09:00 AM", activity: "Lipton's Seat Viewpoint", cost: 1500 },
          { time: "11:00 AM", activity: "Dambatenne Tea Factory", cost: 500 },
          { time: "01:00 PM", activity: "Farewell Lunch", cost: 1200 },
          { time: "03:00 PM", activity: "Departure", cost: 0 },
        ],
      },
    ],
    budget: {
      transport: 6000,
      food: 8500,
      stay: 8000,
      activities: 6000,
    },
  },
  "Mirissa": {
    days: [
      {
        day: 1,
        title: "Beach Paradise",
        activities: [
          { time: "09:00 AM", activity: "Arrival & Check-in", cost: 0 },
          { time: "10:30 AM", activity: "Mirissa Beach Relaxation", cost: 0 },
          { time: "01:00 PM", activity: "Fresh Seafood Lunch", cost: 1500 },
          { time: "03:00 PM", activity: "Coconut Tree Hill", cost: 0 },
          { time: "05:00 PM", activity: "Parrot Rock Sunset", cost: 0 },
          { time: "07:30 PM", activity: "Beach BBQ Dinner", cost: 2500 },
        ],
      },
      {
        day: 2,
        title: "Whale Watching & Snorkeling",
        activities: [
          { time: "05:30 AM", activity: "Blue Whale Watching Tour", cost: 7500 },
          { time: "11:00 AM", activity: "Brunch at Beach", cost: 1200 },
          { time: "01:00 PM", activity: "Rest at Hotel", cost: 0 },
          { time: "03:00 PM", activity: "Snorkeling Trip", cost: 3000 },
          { time: "06:00 PM", activity: "Beach Sunset", cost: 0 },
          { time: "08:00 PM", activity: "Dinner & Nightlife", cost: 2500 },
        ],
      },
    ],
    budget: {
      transport: 6000,
      food: 8500,
      stay: 11000,
      activities: 13000,
    },
  },
  "Nuwara Eliya": {
    days: [
      {
        day: 1,
        title: "Little England",
        activities: [
          { time: "09:00 AM", activity: "Arrival & Check-in", cost: 0 },
          { time: "10:30 AM", activity: "Victoria Park", cost: 300 },
          { time: "12:30 PM", activity: "Lunch at Grand Hotel", cost: 2000 },
          { time: "02:30 PM", activity: "Gregory Lake Boating", cost: 1000 },
          { time: "05:00 PM", activity: "Post Office & Town Walk", cost: 0 },
          { time: "07:00 PM", activity: "High Tea Experience", cost: 1500 },
          { time: "08:30 PM", activity: "Dinner", cost: 1500 },
        ],
      },
      {
        day: 2,
        title: "Waterfalls & Tea Trails",
        activities: [
          { time: "07:00 AM", activity: "Breakfast", cost: 800 },
          { time: "08:30 AM", activity: "Lovers Leap Waterfall", cost: 0 },
          { time: "10:30 AM", activity: "Pedro Tea Estate Tour", cost: 500 },
          { time: "12:30 PM", activity: "Lunch", cost: 1200 },
          { time: "02:00 PM", activity: "Hakgala Botanical Gardens", cost: 1000 },
          { time: "05:00 PM", activity: "Seetha Amman Temple", cost: 0 },
          { time: "07:00 PM", activity: "Farewell Dinner", cost: 1800 },
        ],
      },
    ],
    budget: {
      transport: 7000,
      food: 10000,
      stay: 12500,
      activities: 6000,
    },
  },
};

// Announcements & Events Mock Data
export const announcements = [
  {
    id: 1,
    title: "Mid-Semester Examinations Schedule",
    content: "Mid-semester examinations will be held from February 15-25, 2026. Detailed schedule will be available on the student portal by February 1st.",
    date: "2026-01-24",
    type: "academic",
    isOfficial: true,
    priority: "high",
  },
  {
    id: 2,
    title: "Library Extended Hours",
    content: "Starting January 27th, the main library will remain open until 11 PM on weekdays to support exam preparation.",
    date: "2026-01-23",
    type: "facility",
    isOfficial: true,
    priority: "medium",
  },
  {
    id: 3,
    title: "Campus Wi-Fi Maintenance",
    content: "Scheduled maintenance on campus Wi-Fi network on January 26th from 2 AM to 6 AM. Plan accordingly.",
    date: "2026-01-22",
    type: "technical",
    isOfficial: true,
    priority: "low",
  },
  {
    id: 4,
    title: "New Parking Regulations",
    content: "New parking permits required starting February 1st. Apply through the facilities portal by January 30th.",
    date: "2026-01-20",
    type: "facility",
    isOfficial: true,
    priority: "medium",
  },
];

export const events = [
  {
    id: 1,
    title: "Tech Fest 2026",
    description: "Annual technology festival featuring hackathons, workshops, and tech talks by industry leaders.",
    date: "2026-02-10",
    endDate: "2026-02-12",
    time: "09:00 AM",
    location: "Main Auditorium & Tech Block",
    type: "festival",
    image: "🚀",
    attendees: 450,
    maxAttendees: 500,
    isRegistered: false,
    registrationDeadline: "2026-02-05",
  },
  {
    id: 2,
    title: "Career Fair 2026",
    description: "Meet recruiters from top tech companies. Bring your resume and dress professionally!",
    date: "2026-02-20",
    time: "10:00 AM - 04:00 PM",
    location: "Convention Center",
    type: "career",
    image: "💼",
    attendees: 280,
    maxAttendees: 400,
    isRegistered: true,
    registrationDeadline: "2026-02-18",
  },
  {
    id: 3,
    title: "Workshop: AI & Machine Learning",
    description: "Hands-on workshop on building ML models using Python and TensorFlow.",
    date: "2026-01-28",
    time: "02:00 PM - 05:00 PM",
    location: "Lab-201",
    type: "workshop",
    image: "🤖",
    attendees: 45,
    maxAttendees: 50,
    isRegistered: false,
    registrationDeadline: "2026-01-27",
  },
  {
    id: 4,
    title: "Sports Day",
    description: "Annual inter-department sports competition. Show your athletic spirit!",
    date: "2026-02-05",
    time: "08:00 AM",
    location: "Sports Complex",
    type: "sports",
    image: "⚽",
    attendees: 320,
    maxAttendees: null,
    isRegistered: false,
    registrationDeadline: "2026-02-03",
  },
  {
    id: 5,
    title: "Cultural Night",
    description: "Celebrate diversity with performances, music, and traditional food from around the world.",
    date: "2026-02-15",
    time: "06:00 PM",
    location: "Open Air Theatre",
    type: "cultural",
    image: "🎭",
    attendees: 180,
    maxAttendees: 300,
    isRegistered: true,
    registrationDeadline: "2026-02-12",
  },
];

// User Profile Mock Data
export const userProfile = {
  id: "STU001",
  name: "Alex Johnson",
  email: "alex.johnson@university.edu",
  department: "Computer Science",
  year: "3rd Year",
  semester: "6th Semester",
  avatar: "https://ui-avatars.com/api/?name=Alex+Johnson&background=4F46E5&color=fff",
  gpa: 3.72,
  credits: 98,
  totalCredits: 140,
};

// ============================================
// ADMIN DASHBOARD MOCK DATA
// ============================================

// All Students Data for Admin
export const allStudents = [
  { id: "STU001", name: "Alex Johnson", email: "alex.johnson@university.edu", department: "Computer Science", year: "3rd Year", status: "Active", gpa: 3.72, joinedDate: "2023-09-01" },
  { id: "STU002", name: "Emma Wilson", email: "emma.wilson@university.edu", department: "Computer Science", year: "2nd Year", status: "Active", gpa: 3.85, joinedDate: "2024-09-01" },
  { id: "STU003", name: "Ryan Garcia", email: "ryan.garcia@university.edu", department: "Information Technology", year: "4th Year", status: "Active", gpa: 3.45, joinedDate: "2022-09-01" },
  { id: "STU004", name: "Sophia Lee", email: "sophia.lee@university.edu", department: "Computer Science", year: "1st Year", status: "Active", gpa: 3.92, joinedDate: "2025-09-01" },
  { id: "STU005", name: "James Miller", email: "james.miller@university.edu", department: "Software Engineering", year: "3rd Year", status: "Suspended", gpa: 2.80, joinedDate: "2023-09-01" },
  { id: "STU006", name: "Olivia Brown", email: "olivia.brown@university.edu", department: "Data Science", year: "2nd Year", status: "Active", gpa: 3.68, joinedDate: "2024-09-01" },
  { id: "STU007", name: "Liam Davis", email: "liam.davis@university.edu", department: "Computer Science", year: "4th Year", status: "Graduated", gpa: 3.55, joinedDate: "2022-09-01" },
  { id: "STU008", name: "Ava Martinez", email: "ava.martinez@university.edu", department: "Cybersecurity", year: "1st Year", status: "Active", gpa: 3.78, joinedDate: "2025-09-01" },
];

// All Shop Owners
export const shopOwners = [
  { id: "SHP001", name: "Campus Canteen", owner: "John Smith", email: "canteen@university.edu", type: "Canteen", status: "Active", totalOrders: 1234, rating: 4.2, revenue: 425000 },
  { id: "SHP002", name: "Pizza Palace", owner: "Maria Garcia", email: "pizza@university.edu", type: "Restaurant", status: "Active", totalOrders: 856, rating: 4.5, revenue: 312000 },
  { id: "SHP003", name: "Healthy Bites", owner: "Lisa Wang", email: "healthy@university.edu", type: "Cafe", status: "Active", totalOrders: 623, rating: 4.7, revenue: 198000 },
  { id: "SHP004", name: "Dragon Wok", owner: "Wei Chen", email: "dragon@university.edu", type: "Restaurant", status: "Inactive", totalOrders: 445, rating: 4.4, revenue: 156000 },
  { id: "SHP005", name: "Tech Gadgets Store", owner: "Mike Johnson", email: "techstore@university.edu", type: "Electronics", status: "Active", totalOrders: 234, rating: 4.6, revenue: 890000 },
  { id: "SHP006", name: "Book Haven", owner: "Sarah Lee", email: "books@university.edu", type: "Bookstore", status: "Active", totalOrders: 567, rating: 4.8, revenue: 234000 },
];

// All Delivery Riders
export const deliveryRiders = [
  { id: "RDR001", name: "Ahmed Khan", email: "ahmed@delivery.edu", phone: "+94 77 123 4567", vehicle: "Motorcycle", status: "Active", rating: 4.8, totalDeliveries: 456, earnings: 125000 },
  { id: "RDR002", name: "Priya Sharma", email: "priya@delivery.edu", phone: "+94 77 234 5678", vehicle: "Bicycle", status: "Active", rating: 4.9, totalDeliveries: 321, earnings: 89000 },
  { id: "RDR003", name: "Kamal Fernando", email: "kamal@delivery.edu", phone: "+94 77 345 6789", vehicle: "Motorcycle", status: "On Delivery", rating: 4.6, totalDeliveries: 534, earnings: 145000 },
  { id: "RDR004", name: "Nimal Perera", email: "nimal@delivery.edu", phone: "+94 77 456 7890", vehicle: "Car", status: "Inactive", rating: 4.5, totalDeliveries: 245, earnings: 78000 },
  { id: "RDR005", name: "Sanjay Patel", email: "sanjay@delivery.edu", phone: "+94 77 567 8901", vehicle: "Motorcycle", status: "Active", rating: 4.7, totalDeliveries: 612, earnings: 167000 },
];

// All Orders for Admin Dashboard
export const allOrders = [
  { id: "ORD001", customer: "Alex Johnson", shop: "Campus Canteen", items: "Chicken Rice Bowl, Fresh Juice", total: 630, status: "Delivered", date: "2026-02-01", time: "12:30 PM", rider: "Ahmed Khan", paymentMethod: "Card" },
  { id: "ORD002", customer: "Emma Wilson", shop: "Pizza Palace", items: "Margherita Pizza, Garlic Bread", total: 1650, status: "Preparing", date: "2026-02-01", time: "01:15 PM", rider: null, paymentMethod: "Cash" },
  { id: "ORD003", customer: "Ryan Garcia", shop: "Healthy Bites", items: "Caesar Salad, Green Juice", total: 1050, status: "Out for Delivery", date: "2026-02-01", time: "12:45 PM", rider: "Priya Sharma", paymentMethod: "Card" },
  { id: "ORD004", customer: "Sophia Lee", shop: "Campus Canteen", items: "Vegetable Curry, Grilled Sandwich", total: 630, status: "Pending", date: "2026-02-01", time: "01:30 PM", rider: null, paymentMethod: "Cash" },
  { id: "ORD005", customer: "James Miller", shop: "Pizza Palace", items: "Pepperoni Pizza, Coke x2", total: 1800, status: "Delivered", date: "2026-01-31", time: "07:30 PM", rider: "Kamal Fernando", paymentMethod: "Card" },
  { id: "ORD006", customer: "Olivia Brown", shop: "Healthy Bites", items: "Avocado Toast, Smoothie Bowl", total: 1300, status: "Cancelled", date: "2026-01-31", time: "11:00 AM", rider: null, paymentMethod: "Cash" },
  { id: "ORD007", customer: "Liam Davis", shop: "Dragon Wok", items: "Fried Rice, Spring Rolls", total: 980, status: "Delivered", date: "2026-01-31", time: "06:15 PM", rider: "Sanjay Patel", paymentMethod: "Card" },
  { id: "ORD008", customer: "Ava Martinez", shop: "Campus Canteen", items: "Chicken Rice Bowl x2", total: 900, status: "Preparing", date: "2026-02-01", time: "01:45 PM", rider: null, paymentMethod: "Cash" },
];

// Ride Bookings for Admin
export const allRideBookings = [
  { id: "RDE001", passenger: "Alex Johnson", pickup: "Student Hostel A", dropoff: "City Mall", vehicle: "Car", fare: 650, status: "Completed", date: "2026-02-01", time: "10:00 AM", rider: "Kamal Fernando" },
  { id: "RDE002", passenger: "Emma Wilson", pickup: "University Main Gate", dropoff: "Central Station", vehicle: "Three-Wheeler", fare: 350, status: "In Progress", date: "2026-02-01", time: "01:30 PM", rider: "Ahmed Khan" },
  { id: "RDE003", passenger: "Ryan Garcia", pickup: "Library Building", dropoff: "Airport", vehicle: "Premium Car", fare: 2500, status: "Confirmed", date: "2026-02-01", time: "03:00 PM", rider: "Sanjay Patel" },
  { id: "RDE004", passenger: "Sophia Lee", pickup: "Sports Complex", dropoff: "City Mall", vehicle: "Bike", fare: 180, status: "Completed", date: "2026-01-31", time: "05:00 PM", rider: "Priya Sharma" },
  { id: "RDE005", passenger: "James Miller", pickup: "Student Hostel A", dropoff: "Bus Terminal", vehicle: "Car", fare: 480, status: "Cancelled", date: "2026-01-31", time: "09:00 AM", rider: null },
];

// Laundry Orders for Admin
export const allLaundryOrders = [
  { id: "LND001", customer: "Alex Johnson", service: "QuickWash Campus", items: "5kg Regular Wash", total: 1250, status: "Ready for Pickup", date: "2026-02-01", pickupTime: "10:00 AM", deliveryTime: "06:00 PM", rider: "Ahmed Khan" },
  { id: "LND002", customer: "Emma Wilson", service: "Premium Dry Clean", items: "2 Shirts, 1 Suit", total: 2400, status: "Processing", date: "2026-02-01", pickupTime: "09:00 AM", deliveryTime: "Pending", rider: null },
  { id: "LND003", customer: "Ryan Garcia", service: "Express Laundry", items: "3kg Express Wash", total: 1350, status: "Picked Up", date: "2026-02-01", pickupTime: "11:00 AM", deliveryTime: "05:00 PM", rider: "Priya Sharma" },
  { id: "LND004", customer: "Sophia Lee", service: "QuickWash Campus", items: "8kg Regular Wash, 2 Bedding", total: 3600, status: "Delivered", date: "2026-01-31", pickupTime: "02:00 PM", deliveryTime: "06:00 PM", rider: "Kamal Fernando" },
  { id: "LND005", customer: "Olivia Brown", service: "Premium Dry Clean", items: "3 Dresses", total: 1800, status: "Out for Delivery", date: "2026-02-01", pickupTime: "08:00 AM", deliveryTime: "04:00 PM", rider: "Sanjay Patel" },
];

// Shop Owner Dashboard Data
export const shopOwnerData = {
  shopInfo: {
    id: "SHP002",
    name: "Pizza Palace",
    owner: "Maria Garcia",
    email: "pizza@university.edu",
    phone: "+94 77 123 4567",
    type: "Restaurant",
    status: "Active",
    rating: 4.5,
    totalReviews: 189,
    joinedDate: "2024-06-15",
    description: "Authentic Italian pizzas made with fresh ingredients",
    openingHours: "10:00 AM - 10:00 PM",
    deliveryRadius: "5km",
  },
  stats: {
    todayOrders: 24,
    todayRevenue: 28500,
    pendingOrders: 5,
    avgRating: 4.5,
    weeklyOrders: 156,
    weeklyRevenue: 185000,
    monthlyOrders: 612,
    monthlyRevenue: 745000,
  },
  recentOrders: [
    { id: "ORD002", customer: "Emma Wilson", items: "Margherita Pizza, Garlic Bread", total: 1650, status: "Preparing", time: "5 mins ago", address: "Block A, Room 203" },
    { id: "ORD009", customer: "Liam Davis", items: "Pepperoni Pizza x2, Coke x3", total: 3450, status: "Pending", time: "10 mins ago", address: "Block C, Room 415" },
    { id: "ORD010", customer: "Ava Martinez", items: "Garlic Bread x2", total: 900, status: "Ready", time: "15 mins ago", address: "Block B, Room 102" },
    { id: "ORD011", customer: "Noah Wilson", items: "Margherita Pizza, Pepperoni Pizza", total: 2700, status: "Out for Delivery", time: "25 mins ago", address: "Block D, Room 308" },
  ],
  menuItems: [
    { id: 1, name: "Margherita Pizza", category: "Pizza", price: 1200, originalPrice: null, available: true, popular: true, image: "🍕" },
    { id: 2, name: "Pepperoni Pizza", category: "Pizza", price: 1500, originalPrice: null, available: true, popular: true, image: "🍕" },
    { id: 3, name: "BBQ Chicken Pizza", category: "Pizza", price: 1600, originalPrice: 1800, available: true, popular: false, image: "🍕" },
    { id: 4, name: "Veggie Supreme Pizza", category: "Pizza", price: 1400, originalPrice: null, available: true, popular: false, image: "🥬" },
    { id: 5, name: "Garlic Bread", category: "Sides", price: 450, originalPrice: null, available: true, popular: false, image: "🥖" },
    { id: 6, name: "Cheese Sticks", category: "Sides", price: 550, originalPrice: null, available: false, popular: false, image: "🧀" },
    { id: 7, name: "Coke", category: "Drinks", price: 150, originalPrice: null, available: true, popular: false, image: "🥤" },
    { id: 8, name: "Sprite", category: "Drinks", price: 150, originalPrice: null, available: true, popular: false, image: "🥤" },
  ],
  marketplaceItems: [
    { id: 1, name: "Pizza Oven Thermometer", category: "Equipment", price: 2500, stock: 5, status: "Active", sales: 12, image: "🌡️" },
    { id: 2, name: "Chef Apron Set", category: "Accessories", price: 1800, stock: 15, status: "Active", sales: 23, image: "👨‍🍳" },
    { id: 3, name: "Italian Recipe Book", category: "Books", price: 3500, stock: 8, status: "Active", sales: 7, image: "📚" },
  ],
};

// Delivery Rider Dashboard Data  
export const riderDashboardData = {
  riderInfo: {
    id: "RDR001",
    name: "Ahmed Khan",
    email: "ahmed@delivery.edu",
    phone: "+94 77 123 4567",
    vehicle: "Motorcycle",
    vehicleNumber: "WP-AB-1234",
    status: "Active",
    rating: 4.8,
    totalReviews: 156,
    joinedDate: "2025-03-15",
    licenseExpiry: "2027-05-20",
  },
  stats: {
    todayDeliveries: 8,
    todayEarnings: 2400,
    activeDelivery: 1,
    pendingPickups: 2,
    weeklyDeliveries: 45,
    weeklyEarnings: 13500,
    monthlyDeliveries: 178,
    monthlyEarnings: 54000,
  },
  activeDeliveries: [
    { id: "DEL001", type: "Food", orderId: "ORD003", customer: "Ryan Garcia", pickup: "Healthy Bites", dropoff: "Block B, Room 305", status: "Picked Up", estimatedTime: "10 mins", amount: 1050, distance: "1.2 km", pickupTime: "12:45 PM" },
  ],
  pendingPickups: [
    { id: "DEL002", type: "Laundry", orderId: "LND001", customer: "Alex Johnson", pickup: "QuickWash Campus", dropoff: "Block A, Room 201", status: "Ready for Pickup", scheduledTime: "02:00 PM", amount: 1250, distance: "0.8 km" },
    { id: "DEL003", type: "Food", orderId: "ORD011", customer: "Noah Wilson", pickup: "Pizza Palace", dropoff: "Block D, Room 308", status: "Ready for Pickup", scheduledTime: "02:15 PM", amount: 2700, distance: "1.5 km" },
  ],
  completedToday: [
    { id: "DEL004", type: "Ride", orderId: "RDE002", customer: "Emma Wilson", pickup: "University Main Gate", dropoff: "Central Station", completedAt: "11:30 AM", amount: 350, distance: "3.2 km", rating: 5 },
    { id: "DEL005", type: "Food", orderId: "ORD001", customer: "Alex Johnson", pickup: "Campus Canteen", dropoff: "Block A, Room 201", completedAt: "12:15 PM", amount: 630, distance: "0.5 km", rating: 5 },
    { id: "DEL006", type: "Laundry", orderId: "LND003", customer: "Ryan Garcia", pickup: "Express Laundry", dropoff: "Block B, Room 305", completedAt: "10:45 AM", amount: 1350, distance: "1.0 km", rating: 4 },
  ],
  upcomingRides: [
    { id: "RDE003", passenger: "Ryan Garcia", pickup: "Library Building", dropoff: "Airport", scheduledTime: "03:00 PM", vehicle: "Premium Car", fare: 2500, distance: "25 km" },
  ],
  earningsBreakdown: {
    foodDeliveries: 15000,
    laundryDeliveries: 8500,
    rideBookings: 12000,
    tips: 3500,
    bonuses: 2000,
  },
};

// Marketplace Items for Shop Owner (items they're selling in marketplace, not menu)
export const shopMarketplaceItems = [
  { id: 1, name: "Pizza Oven Thermometer", category: "Equipment", price: 2500, stock: 5, status: "Active", sales: 12, image: "🌡️" },
  { id: 2, name: "Chef Apron Set", category: "Accessories", price: 1800, stock: 15, status: "Active", sales: 23, image: "👨‍🍳" },
  { id: 3, name: "Italian Recipe Book", category: "Books", price: 3500, stock: 8, status: "Active", sales: 7, image: "📚" },
];

// Admin Analytics Data
export const adminAnalytics = {
  platformStats: {
    totalUsers: 12847,
    activeToday: 3421,
    totalOrders: 45678,
    totalRevenue: 12450000,
    activeShops: 24,
    activeRiders: 18,
  },
  ordersByStatus: {
    pending: 45,
    preparing: 32,
    outForDelivery: 28,
    delivered: 8956,
    cancelled: 234,
  },
  revenueByCategory: {
    food: 5600000,
    marketplace: 3200000,
    laundry: 1800000,
    rides: 1850000,
  },
  topShops: [
    { name: "Campus Canteen", orders: 1234, revenue: 425000 },
    { name: "Pizza Palace", orders: 856, revenue: 312000 },
    { name: "Healthy Bites", orders: 623, revenue: 198000 },
  ],
  topRiders: [
    { name: "Sanjay Patel", deliveries: 612, earnings: 167000 },
    { name: "Kamal Fernando", deliveries: 534, earnings: 145000 },
    { name: "Ahmed Khan", deliveries: 456, earnings: 125000 },
  ],
};
