// Dashboard Mock Data
export const todayClasses = [
  {
    id: 1,
    name: "Data Structures & Algorithms",
    code: "CS201",
    time: "09:00 AM - 10:30 AM",
    room: "LH-101",
    professor: "Dr. Sarah Johnson",
    color: "#4F46E5",
  },
  {
    id: 2,
    name: "Database Management Systems",
    code: "CS301",
    time: "11:00 AM - 12:30 PM",
    room: "LH-205",
    professor: "Prof. Michael Chen",
    color: "#22C55E",
  },
  {
    id: 3,
    name: "Web Development",
    code: "CS401",
    time: "02:00 PM - 03:30 PM",
    room: "Lab-302",
    professor: "Dr. Emily Rodriguez",
    color: "#F59E0B",
  },
];

export const upcomingDeadlines = [
  {
    id: 1,
    title: "DSA Assignment 3",
    course: "CS201",
    dueDate: "2026-01-27",
    dueTime: "11:59 PM",
    progress: 75,
    status: "in-progress",
  },
  {
    id: 2,
    title: "Database Project Proposal",
    course: "CS301",
    dueDate: "2026-01-28",
    dueTime: "05:00 PM",
    progress: 30,
    status: "in-progress",
  },
  {
    id: 3,
    title: "Web Dev Portfolio",
    course: "CS401",
    dueDate: "2026-01-30",
    dueTime: "11:59 PM",
    progress: 0,
    status: "not-started",
  },
  {
    id: 4,
    title: "Research Paper Review",
    course: "CS501",
    dueDate: "2026-02-01",
    dueTime: "11:59 PM",
    progress: 100,
    status: "completed",
  },
];

export const notifications = [
  {
    id: 1,
    type: "announcement",
    title: "Campus Closed Monday",
    message: "University will remain closed on Monday due to maintenance.",
    time: "2 hours ago",
    read: false,
  },
  {
    id: 2,
    type: "deadline",
    title: "Assignment Due Soon",
    message: "DSA Assignment 3 is due in 2 days.",
    time: "5 hours ago",
    read: false,
  },
  {
    id: 3,
    type: "event",
    title: "Tech Fest Registration",
    message: "Registration for Tech Fest 2026 is now open!",
    time: "1 day ago",
    read: true,
  },
  {
    id: 4,
    type: "group",
    title: "Study Group Meeting",
    message: "DSA study group meeting scheduled for tomorrow at 4 PM.",
    time: "1 day ago",
    read: true,
  },
];

// Timetable Mock Data
export const weeklySchedule = [
  {
    day: "Monday",
    classes: [
      { id: 1, name: "Data Structures", code: "CS201", time: "09:00 - 10:30", room: "LH-101", color: "#4F46E5" },
      { id: 2, name: "Database Systems", code: "CS301", time: "11:00 - 12:30", room: "LH-205", color: "#22C55E" },
      { id: 3, name: "Web Development", code: "CS401", time: "14:00 - 15:30", room: "Lab-302", color: "#F59E0B" },
    ],
  },
  {
    day: "Tuesday",
    classes: [
      { id: 4, name: "Computer Networks", code: "CS302", time: "10:00 - 11:30", room: "LH-103", color: "#EF4444" },
      { id: 5, name: "Software Engineering", code: "CS402", time: "13:00 - 14:30", room: "LH-201", color: "#8B5CF6" },
    ],
  },
  {
    day: "Wednesday",
    classes: [
      { id: 6, name: "Data Structures Lab", code: "CS201L", time: "09:00 - 12:00", room: "Lab-101", color: "#4F46E5" },
      { id: 7, name: "Web Development", code: "CS401", time: "14:00 - 15:30", room: "Lab-302", color: "#F59E0B" },
    ],
  },
  {
    day: "Thursday",
    classes: [
      { id: 8, name: "Database Systems", code: "CS301", time: "09:00 - 10:30", room: "LH-205", color: "#22C55E" },
      { id: 9, name: "Computer Networks", code: "CS302", time: "11:00 - 12:30", room: "LH-103", color: "#EF4444" },
      { id: 10, name: "Software Engineering", code: "CS402", time: "14:00 - 15:30", room: "LH-201", color: "#8B5CF6" },
    ],
  },
  {
    day: "Friday",
    classes: [
      { id: 11, name: "Data Structures", code: "CS201", time: "09:00 - 10:30", room: "LH-101", color: "#4F46E5" },
      { id: 12, name: "Database Lab", code: "CS301L", time: "11:00 - 14:00", room: "Lab-201", color: "#22C55E" },
    ],
  },
];

// Assignments Mock Data
export const assignments = [
  {
    id: 1,
    title: "DSA Assignment 3: Binary Trees",
    course: "Data Structures & Algorithms",
    courseCode: "CS201",
    dueDate: "2026-01-27",
    dueTime: "11:59 PM",
    description: "Implement binary tree operations including insertion, deletion, and traversal algorithms.",
    progress: 75,
    status: "in-progress",
    priority: "high",
  },
  {
    id: 2,
    title: "Database Project Proposal",
    course: "Database Management Systems",
    courseCode: "CS301",
    dueDate: "2026-01-28",
    dueTime: "05:00 PM",
    description: "Submit a detailed proposal for the semester database project including ER diagrams.",
    progress: 30,
    status: "in-progress",
    priority: "high",
  },
  {
    id: 3,
    title: "Web Development Portfolio",
    course: "Web Development",
    courseCode: "CS401",
    dueDate: "2026-01-30",
    dueTime: "11:59 PM",
    description: "Create a personal portfolio website showcasing your projects and skills.",
    progress: 0,
    status: "not-started",
    priority: "medium",
  },
  {
    id: 4,
    title: "Network Protocol Analysis",
    course: "Computer Networks",
    courseCode: "CS302",
    dueDate: "2026-02-02",
    dueTime: "11:59 PM",
    description: "Analyze TCP/IP protocols using Wireshark and document findings.",
    progress: 0,
    status: "not-started",
    priority: "low",
  },
  {
    id: 5,
    title: "Software Requirements Document",
    course: "Software Engineering",
    courseCode: "CS402",
    dueDate: "2026-01-25",
    dueTime: "11:59 PM",
    description: "Complete SRS document for the team project.",
    progress: 100,
    status: "completed",
    priority: "high",
  },
];

// Courses Mock Data
export const courses = [
  {
    id: 1,
    name: "Data Structures & Algorithms",
    code: "CS201",
    professor: "Dr. Sarah Johnson",
    credits: 4,
    color: "#4F46E5",
    progress: 65,
    grade: "A-",
  },
  {
    id: 2,
    name: "Database Management Systems",
    code: "CS301",
    professor: "Prof. Michael Chen",
    credits: 4,
    color: "#22C55E",
    progress: 70,
    grade: "B+",
  },
  {
    id: 3,
    name: "Web Development",
    code: "CS401",
    professor: "Dr. Emily Rodriguez",
    credits: 3,
    color: "#F59E0B",
    progress: 55,
    grade: "A",
  },
  {
    id: 4,
    name: "Computer Networks",
    code: "CS302",
    professor: "Prof. David Kim",
    credits: 3,
    color: "#EF4444",
    progress: 60,
    grade: "B",
  },
  {
    id: 5,
    name: "Software Engineering",
    code: "CS402",
    professor: "Dr. Lisa Wang",
    credits: 3,
    color: "#8B5CF6",
    progress: 75,
    grade: "A-",
  },
];

// Notes Mock Data
export const notes = [
  {
    id: 1,
    title: "DSA Complete Notes - Trees & Graphs",
    course: "CS201",
    courseName: "Data Structures & Algorithms",
    uploader: "Alex Thompson",
    uploadDate: "2026-01-20",
    fileType: "pdf",
    fileSize: "2.4 MB",
    upvotes: 156,
    downloads: 342,
  },
  {
    id: 2,
    title: "SQL Cheat Sheet",
    course: "CS301",
    courseName: "Database Management Systems",
    uploader: "Emma Wilson",
    uploadDate: "2026-01-18",
    fileType: "pdf",
    fileSize: "1.2 MB",
    upvotes: 203,
    downloads: 489,
  },
  {
    id: 3,
    title: "React Hooks Tutorial",
    course: "CS401",
    courseName: "Web Development",
    uploader: "Ryan Garcia",
    uploadDate: "2026-01-22",
    fileType: "docx",
    fileSize: "856 KB",
    upvotes: 89,
    downloads: 178,
  },
  {
    id: 4,
    title: "TCP/IP Protocol Summary",
    course: "CS302",
    courseName: "Computer Networks",
    uploader: "Sophia Lee",
    uploadDate: "2026-01-15",
    fileType: "pdf",
    fileSize: "3.1 MB",
    upvotes: 124,
    downloads: 267,
  },
  {
    id: 5,
    title: "Agile Methodology Notes",
    course: "CS402",
    courseName: "Software Engineering",
    uploader: "James Miller",
    uploadDate: "2026-01-19",
    fileType: "pptx",
    fileSize: "5.2 MB",
    upvotes: 67,
    downloads: 145,
  },
];

// Study Groups Mock Data
export const studyGroups = [
  {
    id: 1,
    name: "DSA Warriors",
    course: "CS201",
    courseName: "Data Structures & Algorithms",
    members: 12,
    maxMembers: 15,
    nextMeeting: "2026-01-26 16:00",
    meetingLocation: "Library Room 3A",
    description: "Weekly problem-solving sessions for DSA assignments and exam prep.",
    isJoined: true,
    avatar: "🔥",
  },
  {
    id: 2,
    name: "SQL Masters",
    course: "CS301",
    courseName: "Database Management Systems",
    members: 8,
    maxMembers: 10,
    nextMeeting: "2026-01-27 14:00",
    meetingLocation: "Online - Discord",
    description: "Focus on SQL queries, normalization, and database design.",
    isJoined: false,
    avatar: "💾",
  },
  {
    id: 3,
    name: "Web Dev Wizards",
    course: "CS401",
    courseName: "Web Development",
    members: 15,
    maxMembers: 20,
    nextMeeting: "2026-01-28 18:00",
    meetingLocation: "Tech Hub Cafe",
    description: "Build projects together, share resources, and learn new frameworks.",
    isJoined: true,
    avatar: "🚀",
  },
  {
    id: 4,
    name: "Network Ninjas",
    course: "CS302",
    courseName: "Computer Networks",
    members: 6,
    maxMembers: 12,
    nextMeeting: "2026-01-29 15:00",
    meetingLocation: "Lab-103",
    description: "Hands-on networking labs and protocol analysis sessions.",
    isJoined: false,
    avatar: "🌐",
  },
];

// Chat Messages for Study Groups
export const groupChatMessages = [
  {
    id: 1,
    groupId: 1,
    sender: "Alex Thompson",
    message: "Hey everyone! Ready for today's session on AVL trees?",
    time: "3:45 PM",
    isMe: false,
  },
  {
    id: 2,
    groupId: 1,
    sender: "You",
    message: "Yes! I've been struggling with rotations though 😅",
    time: "3:47 PM",
    isMe: true,
  },
  {
    id: 3,
    groupId: 1,
    sender: "Emma Wilson",
    message: "I found a great visualization tool, will share during the meeting!",
    time: "3:50 PM",
    isMe: false,
  },
  {
    id: 4,
    groupId: 1,
    sender: "Ryan Garcia",
    message: "Perfect timing, I need help with the assignment too",
    time: "3:52 PM",
    isMe: false,
  },
];

// Marketplace Mock Data
export const marketplaceItems = [
  {
    id: 1,
    title: "DSA Textbook - Cormen (Like New)",
    category: "Textbooks",
    price: 4500,
    originalPrice: 8900,
    seller: "John Smith",
    sellerRating: 4.8,
    sellerReviews: 23,
    condition: "Like New",
    image: "📚",
    postedDate: "2026-01-23",
    description: "Introduction to Algorithms by Cormen. Used for one semester, no highlights or marks.",
  },
  {
    id: 2,
    title: "MacBook Pro 2024 M3",
    category: "Devices",
    price: 450000,
    originalPrice: 650000,
    seller: "Sarah Lee",
    sellerRating: 4.9,
    sellerReviews: 15,
    condition: "Excellent",
    image: "💻",
    postedDate: "2026-01-22",
    description: "14-inch MacBook Pro, M3 chip, 16GB RAM. Comes with charger and case.",
  },
  {
    id: 3,
    title: "Database Systems Notes Bundle",
    category: "Notes",
    price: 1500,
    originalPrice: null,
    seller: "Mike Johnson",
    sellerRating: 4.7,
    sellerReviews: 45,
    condition: "Digital",
    image: "📝",
    postedDate: "2026-01-24",
    description: "Complete semester notes with solved examples and practice problems.",
  },
  {
    id: 4,
    title: "Scientific Calculator TI-84",
    category: "Devices",
    price: 18000,
    originalPrice: 35000,
    seller: "Emma Davis",
    sellerRating: 4.6,
    sellerReviews: 12,
    condition: "Good",
    image: "🔢",
    postedDate: "2026-01-21",
    description: "TI-84 Plus graphing calculator. Works perfectly, minor scratches.",
  },
  {
    id: 5,
    title: "Web Development Bootcamp Notes",
    category: "Notes",
    price: 2000,
    originalPrice: null,
    seller: "Chris Park",
    sellerRating: 4.9,
    sellerReviews: 67,
    condition: "Digital",
    image: "🌐",
    postedDate: "2026-01-20",
    description: "Comprehensive notes covering HTML, CSS, JavaScript, React, and Node.js.",
  },
  {
    id: 6,
    title: "Engineering Drawing Kit",
    category: "Supplies",
    price: 2500,
    originalPrice: 5000,
    seller: "Ana Martinez",
    sellerRating: 4.5,
    sellerReviews: 8,
    condition: "Good",
    image: "📐",
    postedDate: "2026-01-19",
    description: "Complete drawing kit with compass, rulers, and templates.",
  },
];

// Part-time Jobs Mock Data
export const partTimeJobs = [
  {
    id: 1,
    title: "Library Assistant",
    company: "University Library",
    location: "On-campus",
    type: "Part-time",
    pay: 500,
    payType: "hour",
    schedule: ["Weekday", "Evening"],
    description: "Help students find resources, manage book returns, and maintain library organization.",
    requirements: ["Good communication", "Organized", "Basic computer skills"],
    postedDate: "2026-01-22",
    deadline: "2026-02-01",
  },
  {
    id: 2,
    title: "Research Assistant",
    company: "CS Department",
    location: "On-campus",
    type: "Part-time",
    pay: 600,
    payType: "hour",
    schedule: ["Weekday", "Flexible"],
    description: "Assist professors with research projects, data collection, and analysis.",
    requirements: ["Programming skills", "Research interest", "GPA 3.5+"],
    postedDate: "2026-01-20",
    deadline: "2026-01-30",
  },
  {
    id: 3,
    title: "Campus Tour Guide",
    company: "Admissions Office",
    location: "On-campus",
    type: "Part-time",
    pay: 450,
    payType: "hour",
    schedule: ["Weekend", "Flexible"],
    description: "Lead campus tours for prospective students and their families.",
    requirements: ["Outgoing personality", "Knowledge of campus", "Public speaking"],
    postedDate: "2026-01-23",
    deadline: "2026-02-05",
  },
  {
    id: 4,
    title: "Tutoring - Mathematics",
    company: "Academic Support Center",
    location: "On-campus",
    type: "Part-time",
    pay: 750,
    payType: "hour",
    schedule: ["Evening", "Weekend"],
    description: "Provide tutoring sessions for students in calculus and linear algebra.",
    requirements: ["Strong math background", "Teaching experience preferred", "Patient"],
    postedDate: "2026-01-21",
    deadline: "2026-02-10",
  },
  {
    id: 5,
    title: "Social Media Manager",
    company: "Student Union",
    location: "Remote",
    type: "Part-time",
    pay: 550,
    payType: "hour",
    schedule: ["Flexible", "Remote"],
    description: "Manage social media accounts, create content, and engage with student community.",
    requirements: ["Social media savvy", "Creative", "Basic design skills"],
    postedDate: "2026-01-24",
    deadline: "2026-02-15",
  },
  {
    id: 6,
    title: "Cafe Barista",
    company: "Campus Coffee",
    location: "Nearby",
    type: "Part-time",
    pay: 400,
    payType: "hour",
    schedule: ["Weekend", "Morning"],
    description: "Prepare coffee drinks, serve customers, and maintain cleanliness.",
    requirements: ["Customer service", "Fast learner", "Early mornings OK"],
    postedDate: "2026-01-19",
    deadline: "2026-01-28",
  },
];

// Food Ordering Mock Data
export const foodVendors = [
  {
    id: 1,
    name: "Campus Canteen",
    type: "Canteen",
    rating: 4.2,
    reviews: 234,
    deliveryTime: "15-20 min",
    deliveryFee: 0,
    image: "🍽️",
    isOpen: true,
  },
  {
    id: 2,
    name: "Pizza Palace",
    type: "Restaurant",
    rating: 4.5,
    reviews: 189,
    deliveryTime: "25-35 min",
    deliveryFee: 150,
    image: "🍕",
    isOpen: true,
  },
  {
    id: 3,
    name: "Healthy Bites",
    type: "Cafe",
    rating: 4.7,
    reviews: 156,
    deliveryTime: "20-30 min",
    deliveryFee: 100,
    image: "🥗",
    isOpen: true,
  },
  {
    id: 4,
    name: "Dragon Wok",
    type: "Restaurant",
    rating: 4.4,
    reviews: 278,
    deliveryTime: "30-40 min",
    deliveryFee: 200,
    image: "🥡",
    isOpen: false,
  },
];

export const menuItems = [
  // Campus Canteen
  { id: 1, vendorId: 1, name: "Chicken Rice Bowl", price: 450, category: "Main", image: "🍚", popular: true },
  { id: 2, vendorId: 1, name: "Vegetable Curry", price: 350, category: "Main", image: "🍛", popular: false },
  { id: 3, vendorId: 1, name: "Grilled Sandwich", price: 280, category: "Snacks", image: "🥪", popular: true },
  { id: 4, vendorId: 1, name: "Fresh Juice", price: 180, category: "Drinks", image: "🧃", popular: false },
  // Pizza Palace
  { id: 5, vendorId: 2, name: "Margherita Pizza", price: 1200, category: "Pizza", image: "🍕", popular: true },
  { id: 6, vendorId: 2, name: "Pepperoni Pizza", price: 1500, category: "Pizza", image: "🍕", popular: true },
  { id: 7, vendorId: 2, name: "Garlic Bread", price: 450, category: "Sides", image: "🥖", popular: false },
  { id: 8, vendorId: 2, name: "Coke", price: 150, category: "Drinks", image: "🥤", popular: false },
  // Healthy Bites
  { id: 9, vendorId: 3, name: "Caesar Salad", price: 650, category: "Salads", image: "🥗", popular: true },
  { id: 10, vendorId: 3, name: "Avocado Toast", price: 550, category: "Breakfast", image: "🥑", popular: true },
  { id: 11, vendorId: 3, name: "Smoothie Bowl", price: 750, category: "Bowls", image: "🫐", popular: false },
  { id: 12, vendorId: 3, name: "Green Juice", price: 400, category: "Drinks", image: "🥬", popular: false },
];

// Laundry Mock Data
export const laundryServices = [
  {
    id: 1,
    name: "QuickWash Campus",
    rating: 4.6,
    reviews: 189,
    pricePerKg: 250,
    minOrder: 2,
    deliveryTime: "24-48 hours",
    hasPickup: true,
    hasDelivery: true,
    image: "🧺",
  },
  {
    id: 2,
    name: "Premium Dry Clean",
    rating: 4.8,
    reviews: 134,
    pricePerKg: 400,
    minOrder: 1,
    deliveryTime: "48-72 hours",
    hasPickup: true,
    hasDelivery: true,
    image: "👔",
  },
  {
    id: 3,
    name: "Express Laundry",
    rating: 4.4,
    reviews: 256,
    pricePerKg: 300,
    minOrder: 1.5,
    deliveryTime: "12-24 hours",
    hasPickup: true,
    hasDelivery: false,
    image: "⚡",
  },
];

export const laundryPricing = [
  { type: "Regular Wash", pricePerKg: 250 },
  { type: "Dry Clean", pricePerItem: 600 },
  { type: "Iron Only", pricePerItem: 150 },
  { type: "Bedding (per piece)", pricePerItem: 800 },
  { type: "Express (same day)", pricePerKg: 450 },
];

export const laundryOrders = [
  {
    id: "LD001",
    service: "QuickWash Campus",
    status: "ready",
    items: "5kg Regular Wash",
    total: 1250,
    pickupTime: "2026-01-25 10:00 AM",
    deliveryTime: "2026-01-26 06:00 PM",
  },
  {
    id: "LD002",
    service: "Premium Dry Clean",
    status: "processing",
    items: "2 Shirts, 1 Suit",
    total: 2400,
    pickupTime: "2026-01-24 02:00 PM",
    deliveryTime: "2026-01-27 04:00 PM",
  },
];

// Rides Mock Data
export const rideOptions = [
  {
    id: 1,
    type: "Bike",
    icon: "🏍️",
    basePrice: 100,
    pricePerKm: 30,
    eta: "5-10 min",
    capacity: 1,
    description: "Quick and affordable",
  },
  {
    id: 2,
    type: "Three-Wheeler",
    icon: "🛺",
    basePrice: 150,
    pricePerKm: 50,
    eta: "8-15 min",
    capacity: 3,
    description: "Budget-friendly option",
  },
  {
    id: 3,
    type: "Car",
    icon: "🚗",
    basePrice: 250,
    pricePerKm: 80,
    eta: "10-20 min",
    capacity: 4,
    description: "Comfortable rides",
  },
  {
    id: 4,
    type: "Premium Car",
    icon: "🚘",
    basePrice: 400,
    pricePerKm: 120,
    eta: "10-15 min",
    capacity: 4,
    description: "Premium experience",
  },
];

export const popularLocations = [
  { id: 1, name: "University Main Gate", type: "campus" },
  { id: 2, name: "Library Building", type: "campus" },
  { id: 3, name: "Sports Complex", type: "campus" },
  { id: 4, name: "Student Hostel A", type: "campus" },
  { id: 5, name: "City Mall", type: "nearby" },
  { id: 6, name: "Central Station", type: "nearby" },
  { id: 7, name: "Airport", type: "city" },
  { id: 8, name: "Bus Terminal", type: "city" },
];

// Trip Planner Mock Data
export const tripDestinations = [
  { id: 1, name: "Sigiriya", image: "🏰", popular: true },
  { id: 2, name: "Kandy", image: "🛕", popular: true },
  { id: 3, name: "Galle", image: "🏖️", popular: true },
  { id: 4, name: "Ella", image: "🏔️", popular: true },
  { id: 5, name: "Mirissa", image: "🐋", popular: false },
  { id: 6, name: "Nuwara Eliya", image: "🍃", popular: false },
  { id: 7, name: "Anuradhapura", image: "🛕", popular: false },
  { id: 8, name: "Trincomalee", image: "🌊", popular: false },
];

export const tripPlans = {
  "Sigiriya": {
    days: [
      {
        day: 1,
        title: "Ancient Rock Fortress",
        activities: [
          { time: "06:00 AM", activity: "Early climb to Sigiriya Rock", cost: 5000 },
          { time: "09:00 AM", activity: "Explore Frescoes & Mirror Wall", cost: 0 },
          { time: "11:00 AM", activity: "Lion's Paw & Summit", cost: 0 },
          { time: "01:00 PM", activity: "Traditional Rice & Curry Lunch", cost: 800 },
          { time: "03:00 PM", activity: "Pidurangala Rock Hike", cost: 500 },
          { time: "06:00 PM", activity: "Sunset views of Sigiriya", cost: 0 },
          { time: "08:00 PM", activity: "Dinner at Village Restaurant", cost: 1200 },
        ],
      },
      {
        day: 2,
        title: "Safari & Village Life",
        activities: [
          { time: "05:30 AM", activity: "Minneriya Safari (Elephants)", cost: 6000 },
          { time: "10:00 AM", activity: "Breakfast at Hotel", cost: 600 },
          { time: "12:00 PM", activity: "Village cycling tour", cost: 1500 },
          { time: "01:30 PM", activity: "Lunch with local family", cost: 800 },
          { time: "03:00 PM", activity: "Dambulla Cave Temple", cost: 1500 },
          { time: "06:00 PM", activity: "Return & Rest", cost: 0 },
          { time: "08:00 PM", activity: "Sri Lankan Buffet Dinner", cost: 1800 },
        ],
      },
      {
        day: 3,
        title: "Heritage & Departure",
        activities: [
          { time: "08:00 AM", activity: "Breakfast", cost: 600 },
          { time: "10:00 AM", activity: "Polonnaruwa Ancient City", cost: 3500 },
          { time: "01:00 PM", activity: "Lunch", cost: 800 },
          { time: "03:00 PM", activity: "Souvenir Shopping", cost: 2500 },
          { time: "05:00 PM", activity: "Departure", cost: 0 },
        ],
      },
    ],
    budget: {
      transport: 12000,
      food: 8000,
      stay: 9000,
      activities: 18000,
    },
  },
  "Kandy": {
    days: [
      {
        day: 1,
        title: "Sacred City Exploration",
        activities: [
          { time: "09:00 AM", activity: "Arrival & Check-in", cost: 0 },
          { time: "10:30 AM", activity: "Temple of the Tooth Relic", cost: 2000 },
          { time: "01:00 PM", activity: "Lunch at The Empire Cafe", cost: 1200 },
          { time: "03:00 PM", activity: "Royal Botanical Gardens", cost: 1500 },
          { time: "05:30 PM", activity: "Kandy Lake Walk", cost: 0 },
          { time: "07:00 PM", activity: "Kandyan Dance Show", cost: 2000 },
          { time: "09:00 PM", activity: "Dinner", cost: 1500 },
        ],
      },
      {
        day: 2,
        title: "Tea Country Adventure",
        activities: [
          { time: "07:00 AM", activity: "Breakfast at Hotel", cost: 600 },
          { time: "08:30 AM", activity: "Train to Tea Plantation", cost: 500 },
          { time: "10:00 AM", activity: "Tea Factory Tour", cost: 1000 },
          { time: "12:00 PM", activity: "Tea Tasting Experience", cost: 500 },
          { time: "01:30 PM", activity: "Lunch with Valley View", cost: 1500 },
          { time: "03:00 PM", activity: "Spice Garden Visit", cost: 0 },
          { time: "05:00 PM", activity: "Return to Kandy", cost: 500 },
          { time: "08:00 PM", activity: "Dinner at Devon Restaurant", cost: 1800 },
        ],
      },
      {
        day: 3,
        title: "Culture & Crafts",
        activities: [
          { time: "08:00 AM", activity: "Breakfast", cost: 600 },
          { time: "09:30 AM", activity: "Gem Museum Visit", cost: 0 },
          { time: "11:00 AM", activity: "Batik Factory Tour", cost: 0 },
          { time: "01:00 PM", activity: "Local Lunch", cost: 800 },
          { time: "02:30 PM", activity: "Kandy Market Shopping", cost: 3000 },
          { time: "05:00 PM", activity: "Checkout & Departure", cost: 0 },
        ],
      },
    ],
    budget: {
      transport: 8000,
      food: 10000,
      stay: 10500,
      activities: 10500,
    },
  },
  "Galle": {
    days: [
      {
        day: 1,
        title: "Dutch Colonial Heritage",
        activities: [
          { time: "09:00 AM", activity: "Arrival & Check-in", cost: 0 },
          { time: "10:30 AM", activity: "Galle Fort Walking Tour", cost: 0 },
          { time: "12:00 PM", activity: "Dutch Reformed Church", cost: 0 },
          { time: "01:00 PM", activity: "Lunch at Fort Cafe", cost: 1500 },
          { time: "03:00 PM", activity: "Maritime Museum", cost: 500 },
          { time: "05:00 PM", activity: "Flag Rock Sunset", cost: 0 },
          { time: "07:30 PM", activity: "Seafood Dinner at Fort", cost: 2500 },
        ],
      },
      {
        day: 2,
        title: "Beach & Wildlife",
        activities: [
          { time: "07:00 AM", activity: "Breakfast at Hotel", cost: 800 },
          { time: "08:30 AM", activity: "Unawatuna Beach", cost: 0 },
          { time: "11:00 AM", activity: "Japanese Peace Pagoda", cost: 0 },
          { time: "01:00 PM", activity: "Beach Lunch", cost: 1200 },
          { time: "03:00 PM", activity: "Sea Turtle Hatchery", cost: 1000 },
          { time: "05:00 PM", activity: "Stilt Fishermen Watch", cost: 500 },
          { time: "07:00 PM", activity: "Dinner in Galle", cost: 1800 },
        ],
      },
    ],
    budget: {
      transport: 7000,
      food: 9000,
      stay: 12000,
      activities: 6000,
    },
  },
  "Ella": {
    days: [
      {
        day: 1,
        title: "Scenic Train & Hiking",
        activities: [
          { time: "06:00 AM", activity: "Scenic Train from Kandy", cost: 300 },
          { time: "12:00 PM", activity: "Arrival & Check-in", cost: 0 },
          { time: "01:00 PM", activity: "Lunch at Cafe Chill", cost: 1000 },
          { time: "03:00 PM", activity: "Little Adam's Peak Hike", cost: 0 },
          { time: "06:00 PM", activity: "Sunset at Summit", cost: 0 },
          { time: "08:00 PM", activity: "Dinner at Ella Village", cost: 1200 },
        ],
      },
      {
        day: 2,
        title: "Waterfalls & Adventure",
        activities: [
          { time: "05:00 AM", activity: "Ella Rock Sunrise Hike", cost: 0 },
          { time: "09:00 AM", activity: "Breakfast at Hotel", cost: 600 },
          { time: "11:00 AM", activity: "Nine Arch Bridge", cost: 0 },
          { time: "01:00 PM", activity: "Lunch", cost: 800 },
          { time: "02:30 PM", activity: "Ravana Falls", cost: 0 },
          { time: "04:00 PM", activity: "Flying Ravana Zipline", cost: 4000 },
          { time: "06:00 PM", activity: "Rest & Relax", cost: 0 },
          { time: "08:00 PM", activity: "BBQ Dinner", cost: 1800 },
        ],
      },
      {
        day: 3,
        title: "Tea & Departure",
        activities: [
          { time: "07:00 AM", activity: "Breakfast", cost: 600 },
          { time: "09:00 AM", activity: "Lipton's Seat Viewpoint", cost: 1500 },
          { time: "11:00 AM", activity: "Dambatenne Tea Factory", cost: 500 },
          { time: "01:00 PM", activity: "Farewell Lunch", cost: 1200 },
          { time: "03:00 PM", activity: "Departure", cost: 0 },
        ],
      },
    ],
    budget: {
      transport: 6000,
      food: 8500,
      stay: 8000,
      activities: 6000,
    },
  },
  "Mirissa": {
    days: [
      {
        day: 1,
        title: "Beach Paradise",
        activities: [
          { time: "09:00 AM", activity: "Arrival & Check-in", cost: 0 },
          { time: "10:30 AM", activity: "Mirissa Beach Relaxation", cost: 0 },
          { time: "01:00 PM", activity: "Fresh Seafood Lunch", cost: 1500 },
          { time: "03:00 PM", activity: "Coconut Tree Hill", cost: 0 },
          { time: "05:00 PM", activity: "Parrot Rock Sunset", cost: 0 },
          { time: "07:30 PM", activity: "Beach BBQ Dinner", cost: 2500 },
        ],
      },
      {
        day: 2,
        title: "Whale Watching & Snorkeling",
        activities: [
          { time: "05:30 AM", activity: "Blue Whale Watching Tour", cost: 7500 },
          { time: "11:00 AM", activity: "Brunch at Beach", cost: 1200 },
          { time: "01:00 PM", activity: "Rest at Hotel", cost: 0 },
          { time: "03:00 PM", activity: "Snorkeling Trip", cost: 3000 },
          { time: "06:00 PM", activity: "Beach Sunset", cost: 0 },
          { time: "08:00 PM", activity: "Dinner & Nightlife", cost: 2500 },
        ],
      },
    ],
    budget: {
      transport: 6000,
      food: 8500,
      stay: 11000,
      activities: 13000,
    },
  },
  "Nuwara Eliya": {
    days: [
      {
        day: 1,
        title: "Little England",
        activities: [
          { time: "09:00 AM", activity: "Arrival & Check-in", cost: 0 },
          { time: "10:30 AM", activity: "Victoria Park", cost: 300 },
          { time: "12:30 PM", activity: "Lunch at Grand Hotel", cost: 2000 },
          { time: "02:30 PM", activity: "Gregory Lake Boating", cost: 1000 },
          { time: "05:00 PM", activity: "Post Office & Town Walk", cost: 0 },
          { time: "07:00 PM", activity: "High Tea Experience", cost: 1500 },
          { time: "08:30 PM", activity: "Dinner", cost: 1500 },
        ],
      },
      {
        day: 2,
        title: "Waterfalls & Tea Trails",
        activities: [
          { time: "07:00 AM", activity: "Breakfast", cost: 800 },
          { time: "08:30 AM", activity: "Lovers Leap Waterfall", cost: 0 },
          { time: "10:30 AM", activity: "Pedro Tea Estate Tour", cost: 500 },
          { time: "12:30 PM", activity: "Lunch", cost: 1200 },
          { time: "02:00 PM", activity: "Hakgala Botanical Gardens", cost: 1000 },
          { time: "05:00 PM", activity: "Seetha Amman Temple", cost: 0 },
          { time: "07:00 PM", activity: "Farewell Dinner", cost: 1800 },
        ],
      },
    ],
    budget: {
      transport: 7000,
      food: 10000,
      stay: 12500,
      activities: 6000,
    },
  },
};

// Announcements & Events Mock Data
export const announcements = [
  {
    id: 1,
    title: "Mid-Semester Examinations Schedule",
    content: "Mid-semester examinations will be held from February 15-25, 2026. Detailed schedule will be available on the student portal by February 1st.",
    date: "2026-01-24",
    type: "academic",
    isOfficial: true,
    priority: "high",
  },
  {
    id: 2,
    title: "Library Extended Hours",
    content: "Starting January 27th, the main library will remain open until 11 PM on weekdays to support exam preparation.",
    date: "2026-01-23",
    type: "facility",
    isOfficial: true,
    priority: "medium",
  },
  {
    id: 3,
    title: "Campus Wi-Fi Maintenance",
    content: "Scheduled maintenance on campus Wi-Fi network on January 26th from 2 AM to 6 AM. Plan accordingly.",
    date: "2026-01-22",
    type: "technical",
    isOfficial: true,
    priority: "low",
  },
  {
    id: 4,
    title: "New Parking Regulations",
    content: "New parking permits required starting February 1st. Apply through the facilities portal by January 30th.",
    date: "2026-01-20",
    type: "facility",
    isOfficial: true,
    priority: "medium",
  },
];

export const events = [
  {
    id: 1,
    title: "Tech Fest 2026",
    description: "Annual technology festival featuring hackathons, workshops, and tech talks by industry leaders.",
    date: "2026-02-10",
    endDate: "2026-02-12",
    time: "09:00 AM",
    location: "Main Auditorium & Tech Block",
    type: "festival",
    image: "🚀",
    attendees: 450,
    maxAttendees: 500,
    isRegistered: false,
    registrationDeadline: "2026-02-05",
  },
  {
    id: 2,
    title: "Career Fair 2026",
    description: "Meet recruiters from top tech companies. Bring your resume and dress professionally!",
    date: "2026-02-20",
    time: "10:00 AM - 04:00 PM",
    location: "Convention Center",
    type: "career",
    image: "💼",
    attendees: 280,
    maxAttendees: 400,
    isRegistered: true,
    registrationDeadline: "2026-02-18",
  },
  {
    id: 3,
    title: "Workshop: AI & Machine Learning",
    description: "Hands-on workshop on building ML models using Python and TensorFlow.",
    date: "2026-01-28",
    time: "02:00 PM - 05:00 PM",
    location: "Lab-201",
    type: "workshop",
    image: "🤖",
    attendees: 45,
    maxAttendees: 50,
    isRegistered: false,
    registrationDeadline: "2026-01-27",
  },
  {
    id: 4,
    title: "Sports Day",
    description: "Annual inter-department sports competition. Show your athletic spirit!",
    date: "2026-02-05",
    time: "08:00 AM",
    location: "Sports Complex",
    type: "sports",
    image: "⚽",
    attendees: 320,
    maxAttendees: null,
    isRegistered: false,
    registrationDeadline: "2026-02-03",
  },
  {
    id: 5,
    title: "Cultural Night",
    description: "Celebrate diversity with performances, music, and traditional food from around the world.",
    date: "2026-02-15",
    time: "06:00 PM",
    location: "Open Air Theatre",
    type: "cultural",
    image: "🎭",
    attendees: 180,
    maxAttendees: 300,
    isRegistered: true,
    registrationDeadline: "2026-02-12",
  },
];

// User Profile Mock Data
export const userProfile = {
  id: "STU001",
  name: "Alex Johnson",
  email: "alex.johnson@university.edu",
  department: "Computer Science",
  year: "3rd Year",
  semester: "6th Semester",
  avatar: "https://ui-avatars.com/api/?name=Alex+Johnson&background=4F46E5&color=fff",
  gpa: 3.72,
  credits: 98,
  totalCredits: 140,
};
