-- UniLife: app_pages and role_page_permissions
-- Run this in Supabase SQL Editor or via supabase db push if using CLI.

-- Table: app_pages (all navigable pages with unique id)
CREATE TABLE IF NOT EXISTS app_pages (
  id smallint PRIMARY KEY,
  path text NOT NULL UNIQUE,
  label text NOT NULL,
  role text NOT NULL CHECK (role IN ('student','lecturer','admin','vendor','delivery','super_admin')),
  icon text NOT NULL,
  sort_order smallint NOT NULL DEFAULT 0
);

-- Table: role_page_permissions (super_admin can enable/disable pages per role)
CREATE TABLE IF NOT EXISTS role_page_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role text NOT NULL CHECK (role IN ('student','lecturer','admin','vendor','delivery','super_admin')),
  page_id smallint NOT NULL REFERENCES app_pages(id) ON DELETE CASCADE,
  enabled boolean NOT NULL DEFAULT true,
  UNIQUE(role, page_id)
);

CREATE INDEX IF NOT EXISTS idx_role_page_permissions_role ON role_page_permissions(role);
CREATE INDEX IF NOT EXISTS idx_role_page_permissions_page_id ON role_page_permissions(page_id);

-- Seed app_pages (matches lib/pages/registry.ts)
INSERT INTO app_pages (id, path, label, role, icon, sort_order) VALUES
  (1, '/student/dashboard', 'Dashboard', 'student', 'LayoutDashboard', 1),
  (2, '/student/courses', 'Courses', 'student', 'BookOpen', 2),
  (3, '/student/timetable', 'Timetable', 'student', 'Calendar', 3),
  (4, '/student/assignments', 'Assignments', 'student', 'Briefcase', 4),
  (5, '/student/study-groups', 'Study Groups', 'student', 'Users', 5),
  (6, '/student/marketplace', 'Marketplace', 'student', 'ShoppingBag', 6),
  (7, '/student/food-order', 'Food Order', 'student', 'Utensils', 7),
  (8, '/student/laundry', 'Laundry', 'student', 'Truck', 8),
  (9, '/student/rides', 'Rides', 'student', 'Car', 9),
  (10, '/lecturer/dashboard', 'Dashboard', 'lecturer', 'LayoutDashboard', 1),
  (11, '/lecturer/courses', 'My Courses', 'lecturer', 'BookOpen', 2),
  (12, '/lecturer/schedule', 'Schedule', 'lecturer', 'Calendar', 3),
  (13, '/lecturer/students', 'Students', 'lecturer', 'Users', 4),
  (14, '/lecturer/assignments', 'Assignments', 'lecturer', 'Briefcase', 5),
  (15, '/admin/dashboard', 'Dashboard', 'admin', 'LayoutDashboard', 1),
  (16, '/admin/users', 'Users', 'admin', 'Users', 2),
  (17, '/admin/courses', 'Courses', 'admin', 'BookOpen', 3),
  (18, '/admin/reports', 'Reports', 'admin', 'BarChart3', 4),
  (19, '/admin/announcements', 'Announcements', 'admin', 'Bell', 5),
  (20, '/vendor/dashboard', 'Dashboard', 'vendor', 'LayoutDashboard', 1),
  (21, '/vendor/orders', 'Food Orders', 'vendor', 'Package', 2),
  (22, '/vendor/laundry/orders', 'Laundry Orders', 'vendor', 'Truck', 3),
  (23, '/vendor/menu', 'Menu', 'vendor', 'Utensils', 4),
  (24, '/vendor/settings', 'Store Settings', 'vendor', 'Store', 5),
  (25, '/vendor/analytics', 'Analytics', 'vendor', 'BarChart3', 6),
  (26, '/delivery/dashboard', 'Dashboard', 'delivery', 'LayoutDashboard', 1),
  (27, '/delivery/active', 'Food Deliveries', 'delivery', 'Package', 2),
  (28, '/delivery/laundry', 'Laundry Jobs', 'delivery', 'Truck', 3),
  (29, '/delivery/earnings', 'Earnings', 'delivery', 'BarChart3', 4),
  (30, '/super-admin/dashboard', 'Dashboard', 'super_admin', 'LayoutDashboard', 1),
  (31, '/super-admin/users', 'All Users', 'super_admin', 'UserCog', 2),
  (32, '/super-admin/roles', 'Roles & Permissions', 'super_admin', 'Shield', 3),
  (33, '/super-admin/analytics', 'System Analytics', 'super_admin', 'BarChart3', 4),
  (34, '/super-admin/settings', 'Settings', 'super_admin', 'Settings', 5),
  (35, '/super-admin/pages', 'Page Management', 'super_admin', 'LayoutList', 6)
ON CONFLICT (id) DO UPDATE SET path = EXCLUDED.path, label = EXCLUDED.label, role = EXCLUDED.role, icon = EXCLUDED.icon, sort_order = EXCLUDED.sort_order;

-- Seed default permissions: each role has all its pages enabled
INSERT INTO role_page_permissions (role, page_id, enabled)
SELECT p.role, p.id, true
FROM app_pages p
ON CONFLICT (role, page_id) DO UPDATE SET enabled = EXCLUDED.enabled;

-- RLS (optional): allow read for authenticated, write only for super_admin (enforced in app)
ALTER TABLE app_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_page_permissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read app_pages for authenticated" ON app_pages FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow read role_page_permissions for authenticated" ON role_page_permissions FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow insert role_page_permissions for authenticated" ON role_page_permissions FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow update role_page_permissions for authenticated" ON role_page_permissions FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all app_pages for service role" ON app_pages FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow all role_page_permissions for service role" ON role_page_permissions FOR ALL TO service_role USING (true) WITH CHECK (true);
