-- =============================================================================
-- UniLife: dedicated laundry pricing table
-- One pricing row per laundry shop
-- =============================================================================

create table if not exists public.laundry_pricing (
  id bigint generated by default as identity primary key,
  laundry_shop_id bigint not null references public.laundry_shops(id) on delete cascade,

  -- Core pricing
  wash_only_per_kg numeric(10,2) not null default 0 check (wash_only_per_kg >= 0),
  wash_iron_per_kg numeric(10,2) not null default 0 check (wash_iron_per_kg >= 0),
  normal_dress_wash_only numeric(10,2) not null default 0 check (normal_dress_wash_only >= 0),
  normal_dress_wash_iron numeric(10,2) not null default 0 check (normal_dress_wash_iron >= 0),

  -- Gents / ladies / professional
  shirt_per_item numeric(10,2) not null default 0 check (shirt_per_item >= 0),
  trouser_per_item numeric(10,2) not null default 0 check (trouser_per_item >= 0),
  frock_per_item numeric(10,2) not null default 0 check (frock_per_item >= 0),
  saree_per_item numeric(10,2) not null default 0 check (saree_per_item >= 0),
  coat_per_item numeric(10,2) not null default 0 check (coat_per_item >= 0),
  suit_per_item numeric(10,2) not null default 0 check (suit_per_item >= 0),

  -- Household
  bedsheet_per_item numeric(10,2) not null default 0 check (bedsheet_per_item >= 0),
  blanket_per_item numeric(10,2) not null default 0 check (blanket_per_item >= 0),
  curtain_per_item numeric(10,2) not null default 0 check (curtain_per_item >= 0),

  -- Optional operational settings
  pickup_available boolean not null default true,
  delivery_available boolean not null default true,
  express_available boolean not null default false,
  express_multiplier numeric(6,2) not null default 1.00 check (express_multiplier >= 1),
  min_order_amount numeric(10,2) not null default 0 check (min_order_amount >= 0),
  notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (laundry_shop_id)
);

create index if not exists idx_laundry_pricing_shop
  on public.laundry_pricing (laundry_shop_id);

create index if not exists idx_laundry_pricing_updated_at
  on public.laundry_pricing (updated_at desc);

create or replace function public.set_laundry_pricing_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_laundry_pricing_updated_at on public.laundry_pricing;
create trigger trg_laundry_pricing_updated_at
before update on public.laundry_pricing
for each row
execute function public.set_laundry_pricing_updated_at();

-- -----------------------------------------------------------------------------
-- RLS: vendor sees/updates only own shop pricing
-- -----------------------------------------------------------------------------
alter table public.laundry_pricing enable row level security;

drop policy if exists "laundry_pricing_select_owner" on public.laundry_pricing;
create policy "laundry_pricing_select_owner"
on public.laundry_pricing
for select
to authenticated
using (
  exists (
    select 1
    from public.laundry_shops ls
    join public.users u on lower(u.email) = lower(ls.owner_email)
    where ls.id = laundry_shop_id
      and u.auth_id = auth.uid()
  )
);

drop policy if exists "laundry_pricing_insert_owner" on public.laundry_pricing;
create policy "laundry_pricing_insert_owner"
on public.laundry_pricing
for insert
to authenticated
with check (
  exists (
    select 1
    from public.laundry_shops ls
    join public.users u on lower(u.email) = lower(ls.owner_email)
    where ls.id = laundry_shop_id
      and u.auth_id = auth.uid()
  )
);

drop policy if exists "laundry_pricing_update_owner" on public.laundry_pricing;
create policy "laundry_pricing_update_owner"
on public.laundry_pricing
for update
to authenticated
using (
  exists (
    select 1
    from public.laundry_shops ls
    join public.users u on lower(u.email) = lower(ls.owner_email)
    where ls.id = laundry_shop_id
      and u.auth_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.laundry_shops ls
    join public.users u on lower(u.email) = lower(ls.owner_email)
    where ls.id = laundry_shop_id
      and u.auth_id = auth.uid()
  )
);

drop policy if exists "laundry_pricing_service_role_all" on public.laundry_pricing;
create policy "laundry_pricing_service_role_all"
on public.laundry_pricing
for all
to service_role
using (true)
with check (true);

