-- =============================================================================
-- UniLife: Consolidated schema (app_pages, permissions, system_settings, announcements)
-- Run this ONCE in Supabase SQL Editor. Requires: existing "users" table.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. app_pages + role_page_permissions
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app_pages (
  id smallint PRIMARY KEY,
  path text NOT NULL UNIQUE,
  label text NOT NULL,
  role text NOT NULL CHECK (role IN ('student','lecturer','admin','vendor','vendor-food','vendor-laundry','delivery','super_admin')),
  icon text NOT NULL,
  sort_order smallint NOT NULL DEFAULT 0
);
ALTER TABLE app_pages DROP CONSTRAINT IF EXISTS app_pages_role_check;
ALTER TABLE app_pages ADD CONSTRAINT app_pages_role_check CHECK (role IN ('student','lecturer','admin','vendor','vendor-food','vendor-laundry','delivery','super_admin'));

CREATE TABLE IF NOT EXISTS role_page_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role text NOT NULL CHECK (role IN ('student','lecturer','admin','vendor','vendor-food','vendor-laundry','delivery','super_admin')),
  page_id smallint NOT NULL REFERENCES app_pages(id) ON DELETE CASCADE,
  enabled boolean NOT NULL DEFAULT true,
  UNIQUE(role, page_id)
);
ALTER TABLE role_page_permissions DROP CONSTRAINT IF EXISTS role_page_permissions_role_check;
ALTER TABLE role_page_permissions ADD CONSTRAINT role_page_permissions_role_check CHECK (role IN ('student','lecturer','admin','vendor','vendor-food','vendor-laundry','delivery','super_admin'));

CREATE INDEX IF NOT EXISTS idx_role_page_permissions_role ON role_page_permissions(role);
CREATE INDEX IF NOT EXISTS idx_role_page_permissions_page_id ON role_page_permissions(page_id);

INSERT INTO app_pages (id, path, label, role, icon, sort_order) VALUES
  (1, '/student/dashboard', 'Dashboard', 'student', 'LayoutDashboard', 1),
  (2, '/student/courses', 'Courses', 'student', 'BookOpen', 2),
  (3, '/student/timetable', 'Timetable', 'student', 'Calendar', 3),
  (4, '/student/assignments', 'Assignments', 'student', 'Briefcase', 4),
  (5, '/student/study-groups', 'Study Groups', 'student', 'Users', 5),
  (6, '/student/marketplace', 'Marketplace', 'student', 'ShoppingBag', 6),
  (7, '/student/food-order', 'Food Order', 'student', 'Utensils', 7),
  (8, '/student/laundry', 'Laundry', 'student', 'Truck', 8),
  (9, '/student/rides', 'Rides', 'student', 'Car', 9),
  (10, '/lecturer/dashboard', 'Dashboard', 'lecturer', 'LayoutDashboard', 1),
  (11, '/lecturer/courses', 'My Courses', 'lecturer', 'BookOpen', 2),
  (12, '/lecturer/schedule', 'Schedule', 'lecturer', 'Calendar', 3),
  (13, '/lecturer/students', 'Students', 'lecturer', 'Users', 4),
  (14, '/lecturer/assignments', 'Assignments', 'lecturer', 'Briefcase', 5),
  (15, '/admin/dashboard', 'Dashboard', 'admin', 'LayoutDashboard', 1),
  (16, '/admin/users', 'Users', 'admin', 'Users', 2),
  (17, '/admin/timetable', 'Timetable', 'admin', 'Calendar', 3),
  (18, '/admin/reports', 'Reports', 'admin', 'BarChart3', 4),
  (19, '/admin/announcements', 'Announcements', 'admin', 'Bell', 5),
  (20, '/vendor/dashboard', 'Dashboard', 'vendor-food', 'LayoutDashboard', 1),
  (21, '/vendor/orders', 'Orders', 'vendor-food', 'Package', 2),
  (23, '/vendor/products', 'Products', 'vendor-food', 'Utensils', 4),
  (24, '/vendor/my-store', 'My Store', 'vendor-food', 'Store', 5),
  (25, '/vendor/sales-analytics', 'Sales & Analysis', 'vendor-food', 'BarChart3', 6),
  (22, '/vendor/laundry/orders', 'Laundry Orders', 'vendor-laundry', 'Truck', 2),
  (41, '/vendor/fulfillment', 'Fulfillment', 'vendor-laundry', 'Truck', 3),
  (26, '/delivery/dashboard', 'Dashboard', 'delivery', 'LayoutDashboard', 1),
  (27, '/delivery/active', 'Food Deliveries', 'delivery', 'Package', 2),
  (28, '/delivery/laundry', 'Laundry Jobs', 'delivery', 'Truck', 3),
  (29, '/delivery/earnings', 'Earnings', 'delivery', 'BarChart3', 4),
  (30, '/super-admin/dashboard', 'Dashboard', 'super_admin', 'LayoutDashboard', 1),
  (31, '/super-admin/users', 'All Users', 'super_admin', 'UserCog', 2),
  (32, '/super-admin/roles', 'Roles & Permissions', 'super_admin', 'Shield', 3),
  (33, '/super-admin/analytics', 'System Analytics', 'super_admin', 'BarChart3', 4),
  (34, '/super-admin/settings', 'Settings', 'super_admin', 'Settings', 5),
  (35, '/super-admin/pages', 'Page Management', 'super_admin', 'LayoutList', 6),
  (36, '/admin/laundry/add', 'Add Laundry Shop', 'admin', 'Truck', 6),
  (37, '/admin/food-stalls/add', 'Add Food Stall', 'admin', 'Utensils', 7),
  (38, '/admin/timetable/add', 'Add Timetable', 'admin', 'Calendar', 8),
  (39, '/admin/trips/add', 'Add Trip Location', 'admin', 'MapPin', 9),
  (40, '/admin/users/new', 'Add User', 'admin', 'UserPlus', 10)
ON CONFLICT (id) DO UPDATE SET path = EXCLUDED.path, label = EXCLUDED.label, role = EXCLUDED.role, icon = EXCLUDED.icon, sort_order = EXCLUDED.sort_order;

INSERT INTO role_page_permissions (role, page_id, enabled)
SELECT p.role, p.id, true FROM app_pages p
ON CONFLICT (role, page_id) DO UPDATE SET enabled = EXCLUDED.enabled;

-- vendor-laundry: laundry-specific (22, 41) + shared vendor pages (20, 23, 24, 25)
INSERT INTO role_page_permissions (role, page_id, enabled) VALUES
  ('vendor-laundry', 20, true),
  ('vendor-laundry', 22, true),
  ('vendor-laundry', 23, true),
  ('vendor-laundry', 24, true),
  ('vendor-laundry', 25, true),
  ('vendor-laundry', 41, true)
ON CONFLICT (role, page_id) DO UPDATE SET enabled = EXCLUDED.enabled;

-- vendor-food: disable laundry page (22) if it was ever granted
DELETE FROM role_page_permissions WHERE role = 'vendor-food' AND page_id = 22;

ALTER TABLE app_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_page_permissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read app_pages for authenticated" ON app_pages;
DROP POLICY IF EXISTS "Allow all app_pages for service role" ON app_pages;
CREATE POLICY "Allow read app_pages for authenticated" ON app_pages FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow all app_pages for service role" ON app_pages FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow read role_page_permissions for authenticated" ON role_page_permissions;
DROP POLICY IF EXISTS "Allow insert role_page_permissions for authenticated" ON role_page_permissions;
DROP POLICY IF EXISTS "Allow update role_page_permissions for authenticated" ON role_page_permissions;
DROP POLICY IF EXISTS "Allow all role_page_permissions for service role" ON role_page_permissions;
CREATE POLICY "Allow read role_page_permissions for authenticated" ON role_page_permissions FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow insert role_page_permissions for authenticated" ON role_page_permissions FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow update role_page_permissions for authenticated" ON role_page_permissions FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all role_page_permissions for service role" ON role_page_permissions FOR ALL TO service_role USING (true) WITH CHECK (true);

-- -----------------------------------------------------------------------------
-- 2. user_page_permissions
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_page_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  page_id smallint NOT NULL REFERENCES app_pages(id) ON DELETE CASCADE,
  enabled boolean NOT NULL DEFAULT true,
  UNIQUE(user_id, page_id)
);

CREATE INDEX IF NOT EXISTS idx_user_page_permissions_user_id ON user_page_permissions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_page_permissions_page_id ON user_page_permissions(page_id);

ALTER TABLE user_page_permissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read user_page_permissions for authenticated" ON user_page_permissions;
DROP POLICY IF EXISTS "Allow insert user_page_permissions for authenticated" ON user_page_permissions;
DROP POLICY IF EXISTS "Allow update user_page_permissions for authenticated" ON user_page_permissions;
DROP POLICY IF EXISTS "Allow all user_page_permissions for service role" ON user_page_permissions;
CREATE POLICY "Allow read user_page_permissions for authenticated" ON user_page_permissions FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow insert user_page_permissions for authenticated" ON user_page_permissions FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow update user_page_permissions for authenticated" ON user_page_permissions FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all user_page_permissions for service role" ON user_page_permissions FOR ALL TO service_role USING (true) WITH CHECK (true);

-- -----------------------------------------------------------------------------
-- 3. system_settings
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_settings (
  key text PRIMARY KEY,
  value text NOT NULL DEFAULT ''
);

ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read for authenticated" ON system_settings;
CREATE POLICY "Allow read for authenticated" ON system_settings FOR SELECT USING (true);

INSERT INTO system_settings (key, value) VALUES
  ('app_name', 'UniLife'),
  ('support_email', 'support@unilife.edu'),
  ('maintenance_mode', 'false'),
  ('allow_registration', 'true'),
  ('session_timeout_minutes', '60')
ON CONFLICT (key) DO NOTHING;

-- -----------------------------------------------------------------------------
-- 4. announcements
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  body text NOT NULL,
  target_audience text,
  created_by integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_announcements_created_at ON announcements(created_at DESC);

ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read announcements for authenticated" ON announcements;
DROP POLICY IF EXISTS "Allow insert announcements for admin" ON announcements;
DROP POLICY IF EXISTS "Allow update announcements for admin" ON announcements;
DROP POLICY IF EXISTS "Allow delete announcements for admin" ON announcements;
DROP POLICY IF EXISTS "Allow all announcements for service role" ON announcements;
CREATE POLICY "Allow read announcements for authenticated" ON announcements FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow insert announcements for admin" ON announcements FOR INSERT TO authenticated WITH CHECK (
  EXISTS (SELECT 1 FROM users u WHERE u.auth_id = auth.uid() AND u.role IN ('admin','super_admin'))
);
CREATE POLICY "Allow update announcements for admin" ON announcements FOR UPDATE TO authenticated USING (
  EXISTS (SELECT 1 FROM users u WHERE u.auth_id = auth.uid() AND u.role IN ('admin','super_admin'))
);
CREATE POLICY "Allow delete announcements for admin" ON announcements FOR DELETE TO authenticated USING (
  EXISTS (SELECT 1 FROM users u WHERE u.auth_id = auth.uid() AND u.role IN ('admin','super_admin'))
);
CREATE POLICY "Allow all announcements for service role" ON announcements FOR ALL TO service_role USING (true) WITH CHECK (true);

-- -----------------------------------------------------------------------------
-- 5. food_stalls + food_stall_menu_items
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS food_stalls (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_name text NOT NULL,
  owner_name text NOT NULL,
  owner_email text NOT NULL,
  phone text,
  whatsapp text,
  address text,
  city text,
  area text,
  lat double precision,
  lng double precision,
  description text,
  opening_time time,
  closing_time time,
  days_open text[],
  category text,
  logo text,
  banner text,
  gallery text[],
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_food_stalls_owner_email ON food_stalls(owner_email);
ALTER TABLE food_stalls ADD COLUMN IF NOT EXISTS is_open boolean DEFAULT true;

CREATE TABLE IF NOT EXISTS food_stall_menu_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  food_stall_id bigint NOT NULL REFERENCES food_stalls(id) ON DELETE CASCADE,
  name text NOT NULL,
  price decimal(10,2) NOT NULL,
  food_category text,
  image_url text,
  sort_order smallint DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_food_stall_menu_items_stall ON food_stall_menu_items(food_stall_id);

-- -----------------------------------------------------------------------------
-- 6. laundry_shops
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS laundry_shops (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_name text NOT NULL,
  owner_name text NOT NULL,
  owner_email text NOT NULL,
  phone text,
  whatsapp text,
  address text,
  city text,
  area text,
  lat double precision,
  lng double precision,
  services text[],
  price_list jsonb,
  pickup_delivery boolean DEFAULT true,
  delivery_radius decimal(10,2),
  opening_time time,
  closing_time time,
  logo text,
  banner text,
  gallery text[],
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_laundry_shops_owner_email ON laundry_shops(owner_email);
ALTER TABLE laundry_shops ADD COLUMN IF NOT EXISTS is_open boolean DEFAULT true;

ALTER TABLE food_stalls ENABLE ROW LEVEL SECURITY;
ALTER TABLE food_stall_menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE laundry_shops ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read food_stalls" ON food_stalls;
DROP POLICY IF EXISTS "Allow insert food_stalls admin" ON food_stalls;
DROP POLICY IF EXISTS "Allow update food_stalls owner or admin" ON food_stalls;
DROP POLICY IF EXISTS "Allow all food_stalls service" ON food_stalls;
CREATE POLICY "Allow read food_stalls" ON food_stalls FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow insert food_stalls admin" ON food_stalls FOR INSERT TO authenticated WITH CHECK (
  EXISTS (SELECT 1 FROM users u WHERE u.auth_id = auth.uid() AND u.role IN ('admin','super_admin'))
);
CREATE POLICY "Allow update food_stalls owner or admin" ON food_stalls FOR UPDATE TO authenticated USING (
  owner_email = (SELECT email FROM users WHERE auth_id = auth.uid() LIMIT 1) OR
  EXISTS (SELECT 1 FROM users u WHERE u.auth_id = auth.uid() AND u.role IN ('admin','super_admin'))
);
CREATE POLICY "Allow all food_stalls service" ON food_stalls FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow read food_stall_menu_items" ON food_stall_menu_items;
DROP POLICY IF EXISTS "Allow insert food_stall_menu_items" ON food_stall_menu_items;
DROP POLICY IF EXISTS "Allow update food_stall_menu_items" ON food_stall_menu_items;
DROP POLICY IF EXISTS "Allow all food_stall_menu_items" ON food_stall_menu_items;
CREATE POLICY "Allow read food_stall_menu_items" ON food_stall_menu_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow insert food_stall_menu_items" ON food_stall_menu_items FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow update food_stall_menu_items" ON food_stall_menu_items FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow all food_stall_menu_items" ON food_stall_menu_items FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow read laundry_shops" ON laundry_shops;
DROP POLICY IF EXISTS "Allow insert laundry_shops admin" ON laundry_shops;
DROP POLICY IF EXISTS "Allow update laundry_shops owner or admin" ON laundry_shops;
DROP POLICY IF EXISTS "Allow all laundry_shops service" ON laundry_shops;
CREATE POLICY "Allow read laundry_shops" ON laundry_shops FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow insert laundry_shops admin" ON laundry_shops FOR INSERT TO authenticated WITH CHECK (
  EXISTS (SELECT 1 FROM users u WHERE u.auth_id = auth.uid() AND u.role IN ('admin','super_admin'))
);
CREATE POLICY "Allow update laundry_shops owner or admin" ON laundry_shops FOR UPDATE TO authenticated USING (
  owner_email = (SELECT email FROM users WHERE auth_id = auth.uid() LIMIT 1) OR
  EXISTS (SELECT 1 FROM users u WHERE u.auth_id = auth.uid() AND u.role IN ('admin','super_admin'))
);
CREATE POLICY "Allow all laundry_shops service" ON laundry_shops FOR ALL TO service_role USING (true) WITH CHECK (true);

-- -----------------------------------------------------------------------------
-- 7. trips + trip_itinerary (extended schema for admin add)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trips (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  destination text NOT NULL,
  organizer_name text,
  organizer_email text,
  phone text,
  whatsapp text,
  description text,
  trip_type text,
  transport_type text,
  inclusions text,
  address text,
  city text,
  area text,
  lat double precision,
  lng double precision,
  days integer,
  estimated_budget decimal(10,2),
  departure_date date,
  return_date date,
  max_participants integer,
  logo_url text,
  banner_url text,
  gallery_urls text[],
  status text DEFAULT 'draft',
  created_by integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Add columns if table exists with old schema
ALTER TABLE trips ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS address text;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS city text;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS area text;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS lat double precision;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS lng double precision;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS departure_date date;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS return_date date;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS max_participants integer;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS organizer_name text;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS organizer_email text;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS whatsapp text;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS trip_type text;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS transport_type text;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS inclusions text;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS logo_url text;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS banner_url text;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS gallery_urls text[];

CREATE TABLE IF NOT EXISTS trip_itinerary (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id bigint NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  day_number integer NOT NULL,
  activity text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_trips_created_at ON trips(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trip_itinerary_trip_id ON trip_itinerary(trip_id);

ALTER TABLE trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE trip_itinerary ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read trips" ON trips;
DROP POLICY IF EXISTS "Allow insert trips admin" ON trips;
DROP POLICY IF EXISTS "Allow update trips admin" ON trips;
DROP POLICY IF EXISTS "Allow delete trips admin" ON trips;
DROP POLICY IF EXISTS "Allow all trips service" ON trips;
CREATE POLICY "Allow read trips" ON trips FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow insert trips admin" ON trips FOR INSERT TO authenticated WITH CHECK (
  EXISTS (SELECT 1 FROM users u WHERE u.auth_id = auth.uid() AND u.role IN ('admin','super_admin'))
);
CREATE POLICY "Allow update trips admin" ON trips FOR UPDATE TO authenticated USING (
  EXISTS (SELECT 1 FROM users u WHERE u.auth_id = auth.uid() AND u.role IN ('admin','super_admin'))
);
CREATE POLICY "Allow delete trips admin" ON trips FOR DELETE TO authenticated USING (
  EXISTS (SELECT 1 FROM users u WHERE u.auth_id = auth.uid() AND u.role IN ('admin','super_admin'))
);
CREATE POLICY "Allow all trips service" ON trips FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow read trip_itinerary" ON trip_itinerary;
DROP POLICY IF EXISTS "Allow insert trip_itinerary" ON trip_itinerary;
DROP POLICY IF EXISTS "Allow delete trip_itinerary admin" ON trip_itinerary;
DROP POLICY IF EXISTS "Allow all trip_itinerary" ON trip_itinerary;
CREATE POLICY "Allow read trip_itinerary" ON trip_itinerary FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow insert trip_itinerary" ON trip_itinerary FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow delete trip_itinerary admin" ON trip_itinerary FOR DELETE TO authenticated USING (
  EXISTS (SELECT 1 FROM users u WHERE u.auth_id = auth.uid() AND u.role IN ('admin','super_admin'))
);
CREATE POLICY "Allow all trip_itinerary" ON trip_itinerary FOR ALL TO service_role USING (true) WITH CHECK (true);

-- -----------------------------------------------------------------------------
-- 8. laundry_orders (vendor-laundry orders)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS laundry_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  laundry_shop_id bigint NOT NULL REFERENCES laundry_shops(id) ON DELETE CASCADE,
  customer_name text NOT NULL,
  customer_phone text,
  service text NOT NULL,
  items_count integer NOT NULL DEFAULT 1,
  total_amount decimal(10,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'new',
  address text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_laundry_orders_shop ON laundry_orders(laundry_shop_id);
ALTER TABLE laundry_orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow read laundry_orders" ON laundry_orders;
DROP POLICY IF EXISTS "Allow insert update laundry_orders owner" ON laundry_orders;
DROP POLICY IF EXISTS "Allow all laundry_orders service" ON laundry_orders;
CREATE POLICY "Allow read laundry_orders" ON laundry_orders FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow insert update laundry_orders owner" ON laundry_orders FOR ALL TO authenticated USING (
  EXISTS (SELECT 1 FROM laundry_shops ls, users u WHERE ls.id = laundry_shop_id AND u.auth_id = auth.uid() AND lower(u.email) = lower(ls.owner_email))
) WITH CHECK (
  EXISTS (SELECT 1 FROM laundry_shops ls, users u WHERE ls.id = laundry_shop_id AND u.auth_id = auth.uid() AND lower(u.email) = lower(ls.owner_email))
);
CREATE POLICY "Allow all laundry_orders service" ON laundry_orders FOR ALL TO service_role USING (true) WITH CHECK (true);

-- -----------------------------------------------------------------------------
-- 9. food_orders (vendor-food orders)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS food_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  food_stall_id bigint NOT NULL REFERENCES food_stalls(id) ON DELETE CASCADE,
  customer_name text NOT NULL,
  customer_phone text,
  items text,
  total_amount decimal(10,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'new',
  address text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_food_orders_stall ON food_orders(food_stall_id);
ALTER TABLE food_orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow read food_orders" ON food_orders;
DROP POLICY IF EXISTS "Allow insert update food_orders owner" ON food_orders;
DROP POLICY IF EXISTS "Allow all food_orders service" ON food_orders;
CREATE POLICY "Allow read food_orders" ON food_orders FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow insert update food_orders owner" ON food_orders FOR ALL TO authenticated USING (
  EXISTS (SELECT 1 FROM food_stalls fs, users u WHERE fs.id = food_stall_id AND u.auth_id = auth.uid() AND lower(u.email) = lower(fs.owner_email))
) WITH CHECK (
  EXISTS (SELECT 1 FROM food_stalls fs, users u WHERE fs.id = food_stall_id AND u.auth_id = auth.uid() AND lower(u.email) = lower(fs.owner_email))
);
CREATE POLICY "Allow all food_orders service" ON food_orders FOR ALL TO service_role USING (true) WITH CHECK (true);
